#!/usr/bin/env python3
"""
CSV to PostgreSQL Import Script for UroLOG EMR
Imports data from legacy DBISAM CSV exports to urolog_main_db
"""

import csv
import asyncio
import os
from datetime import datetime
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

# Database connection
DATABASE_URL = "postgresql+asyncpg://emr_admin:secure_password@localhost:5440/urolog_db"

CSV_DIR = "/Users/alp/Documents/antigravity/UroLog_v2.0/03.db_import/csv_exports"

def parse_date(date_str):
    """Parse date from MM/DD/YYYY format"""
    if not date_str or date_str.strip() == '':
        return None
    try:
        # Try MM/DD/YYYY format
        return datetime.strptime(date_str.strip(), "%m/%d/%Y").date()
    except ValueError:
        try:
            # Try DD/MM/YYYY format
            return datetime.strptime(date_str.strip(), "%d/%m/%Y").date()
        except ValueError:
            return None

def clean_string(s):
    """Clean string value"""
    if s is None:
        return None
    s = str(s).strip()
    if s == '' or s.lower() == 'null':
        return None
    # Fix encoding issues
    return s.replace('�', 'ı').replace('�', 'ş').replace('�', 'ğ').replace('�', 'ü').replace('�', 'ö').replace('�', 'ç')

def safe_int(value, default=0):
    """Safely convert value to int"""
    if value is None:
        return default
    value_str = str(value).strip()
    if value_str == '' or value_str.lower() == 'null':
        return default
    try:
        return int(value_str)
    except ValueError:
        return default

def read_csv(filename):
    """Read CSV file skipping header comment"""
    filepath = os.path.join(CSV_DIR, filename)
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return []
    
    rows = []
    with open(filepath, 'r', encoding='latin-1') as f:
        # Skip first line (Generated by DBISAM Viewer comment)
        lines = f.readlines()
        if len(lines) < 3:
            return []
        
        # Skip comment line and empty line
        csv_content = ''.join(lines[2:])
        reader = csv.DictReader(csv_content.splitlines())
        for row in reader:
            rows.append(row)
    return rows

async def import_hastalar(session):
    """Import patients from HASTA.CSV"""
    rows = read_csv("HASTA.CSV")
    count = 0
    
    for row in rows:
        hasta_rec_id = safe_int(row.get('HastaRecID', 0))
        if hasta_rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO hastalar (id, tc_kimlik, ad, soyad, cinsiyet, dogum_tarihi, dogum_yeri, 
                                  kan_grubu, medeni_hal, meslek, adres, ev_tel, is_tel, cep_tel, 
                                  email, kimlik_notlar, doktor)
            VALUES (:id, :tc_kimlik, :ad, :soyad, :cinsiyet, :dogum_tarihi, :dogum_yeri,
                    :kan_grubu, :medeni_hal, :meslek, :adres, :ev_tel, :is_tel, :cep_tel,
                    :email, :kimlik_notlar, :doktor)
            ON CONFLICT (id) DO UPDATE SET
                tc_kimlik = EXCLUDED.tc_kimlik,
                ad = EXCLUDED.ad,
                soyad = EXCLUDED.soyad
        """), {
            'id': hasta_rec_id,
            'tc_kimlik': clean_string(row.get('TCKimlik')),
            'ad': clean_string(row.get('Ad')),
            'soyad': clean_string(row.get('Soyad')),
            'cinsiyet': clean_string(row.get('Cinsiyet')),
            'dogum_tarihi': parse_date(row.get('DTarih')),
            'dogum_yeri': clean_string(row.get('DYer')),
            'kan_grubu': clean_string(row.get('Kangrubu')),
            'medeni_hal': clean_string(row.get('MedeniHal')),
            'meslek': clean_string(row.get('Meslek')),
            'adres': clean_string(f"{row.get('Adres1', '')} {row.get('Adres2', '')} {row.get('Adres3', '')}".strip()),
            'ev_tel': clean_string(row.get('Evtelefonu')),
            'is_tel': clean_string(row.get('IsTelefon')),
            'cep_tel': clean_string(row.get('Ceptelefonu')),
            'email': clean_string(row.get('Eposta')),
            'kimlik_notlar': clean_string(row.get('Notlar')),
            'doktor': clean_string(row.get('Doktor'))
        })
        count += 1
    
    print(f"✓ Imported {count} patients (hastalar)")
    return count

async def import_anamnezler(session):
    """Import medical history from ANAMNEZ.CSV"""
    rows = read_csv("ANAMNEZ.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        if hasta_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO anamnezler (hasta_id, alkol, sigara, allerji, kullandigi_ilaclar, ozgecmis, soygecmis)
            VALUES (:hasta_id, :alkol, :sigara, :allerji, :kullandigi_ilaclar, :ozgecmis, :soygecmis)
            ON CONFLICT (hasta_id) DO UPDATE SET
                alkol = EXCLUDED.alkol,
                sigara = EXCLUDED.sigara,
                allerji = EXCLUDED.allerji
        """), {
            'hasta_id': hasta_id,
            'alkol': clean_string(row.get('Alkol')),
            'sigara': clean_string(row.get('Sigara')),
            'allerji': clean_string(row.get('Allerji')),
            'kullandigi_ilaclar': clean_string(row.get('Kilac')),
            'ozgecmis': clean_string(row.get('Ozgecmis')),
            'soygecmis': clean_string(row.get('Soygecmis'))
        })
        count += 1
    
    print(f"✓ Imported {count} anamnez records (anamnezler)")
    return count

async def import_muayeneler(session):
    """Import examinations from MUAYENE.CSV"""
    rows = read_csv("MUAYENE.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        m_rec_id = safe_int(row.get('MRecID', 0))
        if hasta_id == 0 or m_rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO muayeneler (id, hasta_id, tarih, tansiyon, sikayet, oyku, disuri, pollakiuri,
                                   nokturi, hematuri, genital_akinti, kabizlik, tas_oyku, ates,
                                   catallanma, projeksiyon_azalma, kalibre_incelme, idrar_bas_zorluk,
                                   kesik_idrar_yapma, terminal_damlama, residiv_hissi, inkontinans,
                                   kvah, bobrek_sag, bobrek_sol, suprapubik_kitle, ego, rektal_tuse,
                                   tani1, tani2, oneriler, tedavi)
            VALUES (:id, :hasta_id, :tarih, :tansiyon, :sikayet, :oyku, :disuri, :pollakiuri,
                    :nokturi, :hematuri, :genital_akinti, :kabizlik, :tas_oyku, :ates,
                    :catallanma, :projeksiyon_azalma, :kalibre_incelme, :idrar_bas_zorluk,
                    :kesik_idrar_yapma, :terminal_damlama, :residiv_hissi, :inkontinans,
                    :kvah, :bobrek_sag, :bobrek_sol, :suprapubik_kitle, :ego, :rektal_tuse,
                    :tani1, :tani2, :oneriler, :tedavi)
            ON CONFLICT (id) DO UPDATE SET
                sikayet = EXCLUDED.sikayet,
                oyku = EXCLUDED.oyku
        """), {
            'id': m_rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'tansiyon': clean_string(row.get('Tansiyon')),
            'sikayet': clean_string(row.get('Sikayet')),
            'oyku': clean_string(row.get('Oyku')),
            'disuri': clean_string(row.get('Disuri')),
            'pollakiuri': clean_string(row.get('Pollakiuri')),
            'nokturi': clean_string(row.get('Nokturi')),
            'hematuri': clean_string(row.get('Hematuri')),
            'genital_akinti': clean_string(row.get('GenitalAkinti')),
            'kabizlik': clean_string(row.get('Kabizlik')),
            'tas_oyku': clean_string(row.get('TasOyku')),
            'ates': clean_string(row.get('Ates')),
            'catallanma': clean_string(row.get('Catallanma')),
            'projeksiyon_azalma': clean_string(row.get('ProjeksiyonAzalma')),
            'kalibre_incelme': clean_string(row.get('KalibreIncelme')),
            'idrar_bas_zorluk': clean_string(row.get('IdrarBasZorluk')),
            'kesik_idrar_yapma': clean_string(row.get('KesikIdrarYapma')),
            'terminal_damlama': clean_string(row.get('TerminalDamlama')),
            'residiv_hissi': clean_string(row.get('ResidivHissi')),
            'inkontinans': clean_string(row.get('Inkontinans')),
            'kvah': clean_string(row.get('KVAH')),
            'bobrek_sag': clean_string(row.get('BobrekSag')),
            'bobrek_sol': clean_string(row.get('BobrekSol')),
            'suprapubik_kitle': clean_string(row.get('SuprapubikKitle')),
            'ego': clean_string(row.get('EGO')),
            'rektal_tuse': clean_string(row.get('DRE')),
            'tani1': clean_string(row.get('Tani1')),
            'tani2': clean_string(row.get('Tani2')),
            'oneriler': clean_string(row.get('Prosedur') or row.get('Sonuc')),
            'tedavi': clean_string(row.get('Recete') or row.get('BulguNot'))
        })
        count += 1
    
    print(f"✓ Imported {count} examinations (muayeneler)")
    return count

async def import_operasyonlar(session):
    """Import operations from OPERASYON.CSV"""
    rows = read_csv("OPERASYON.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0))
        if hasta_id == 0 or rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO operasyonlar (id, hasta_id, tarih, pre_op_tani, post_op_tani, ameliyat,
                                     ekip, hemsire, anestezi_ekip, anestezi_tur, notlar, 
                                     patoloji, post_op, video_url)
            VALUES (:id, :hasta_id, :tarih, :pre_op_tani, :post_op_tani, :ameliyat,
                    :ekip, :hemsire, :anestezi_ekip, :anestezi_tur, :notlar,
                    :patoloji, :post_op, :video_url)
            ON CONFLICT (id) DO UPDATE SET
                ameliyat = EXCLUDED.ameliyat,
                notlar = EXCLUDED.notlar
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'pre_op_tani': clean_string(row.get('AOTani')),
            'post_op_tani': clean_string(row.get('ASTani')),
            'ameliyat': clean_string(row.get('Ameliyat')),
            'ekip': clean_string(row.get('OpEkip')),
            'hemsire': clean_string(row.get('Hemsire')),
            'anestezi_ekip': clean_string(row.get('AnesteziEkip')),
            'anestezi_tur': clean_string(row.get('AnesteziTur')),
            'notlar': clean_string(row.get('Notlar')),
            'patoloji': clean_string(row.get('Patoloji')),
            'post_op': clean_string(row.get('PostOp')),
            'video_url': clean_string(row.get('OpVideo'))
        })
        count += 1
    
    print(f"✓ Imported {count} operations (operasyonlar)")
    return count

async def import_sperm_analizleri(session):
    """Import sperm analysis from SPERM.CSV"""
    rows = read_csv("SPERM.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0))
        if hasta_id == 0 or rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO sperm_analizleri (id, hasta_id, tarih, perhiz, volum, likefaksiyon,
                                         viskozite, aglutinasyon, yuvarlak_hucre, sayi,
                                         motilite, p_motilite, tpmss, kruger, metod)
            VALUES (:id, :hasta_id, :tarih, :perhiz, :volum, :likefaksiyon,
                    :viskozite, :aglutinasyon, :yuvarlak_hucre, :sayi,
                    :motilite, :p_motilite, :tpmss, :kruger, :metod)
            ON CONFLICT (id) DO UPDATE SET
                volum = EXCLUDED.volum,
                sayi = EXCLUDED.sayi
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'perhiz': clean_string(row.get('Perhiz')),
            'volum': clean_string(row.get('Volum')),
            'likefaksiyon': clean_string(row.get('Likefaksiyon')),
            'viskozite': clean_string(row.get('Viskozite')),
            'aglutinasyon': clean_string(row.get('Aglutinasyon')),
            'yuvarlak_hucre': clean_string(row.get('YuvarlakHucre')),
            'sayi': clean_string(row.get('Sayi')),
            'motilite': clean_string(row.get('Motilite')),
            'p_motilite': clean_string(row.get('PMotilite')),
            'tpmss': clean_string(row.get('TPMSS')),
            'kruger': clean_string(row.get('Kruger')),
            'metod': clean_string(row.get('Metod'))
        })
        count += 1
    
    print(f"✓ Imported {count} sperm analyses (sperm_analizleri)")
    return count

async def import_idrar_tahlilleri(session):
    """Import urine analysis from IDRAR.CSV"""
    rows = read_csv("IDRAR.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0))
        if hasta_id == 0 or rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO idrar_tahlilleri (id, hasta_id, tarih, dansite, ph, sediment, notlar,
                                         steril, koloni, bakteri, antibiyogram)
            VALUES (:id, :hasta_id, :tarih, :dansite, :ph, :sediment, :notlar,
                    :steril, :koloni, :bakteri, :antibiyogram)
            ON CONFLICT (id) DO UPDATE SET
                dansite = EXCLUDED.dansite,
                sediment = EXCLUDED.sediment
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'dansite': clean_string(row.get('Dansite')),
            'ph': clean_string(row.get('pH')),
            'sediment': clean_string(row.get('Sediment')),
            'notlar': clean_string(row.get('Notlar')),
            'steril': clean_string(row.get('Steril')),
            'koloni': clean_string(row.get('Koloni')),
            'bakteri': clean_string(row.get('Bakteri')),
            'antibiyogram': clean_string(row.get('Antibiyogram'))
        })
        count += 1
    
    print(f"✓ Imported {count} urine analyses (idrar_tahlilleri)")
    return count

async def import_goruntuleme(session):
    """Import imaging results from GLABIST.CSV"""
    rows = read_csv("GLABIST.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0))
        if hasta_id == 0 or rec_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO goruntuleme_sonuclari (id, hasta_id, tarih, tetkik_adi, sonuc, sembol)
            VALUES (:id, :hasta_id, :tarih, :tetkik_adi, :sonuc, :sembol)
            ON CONFLICT (id) DO UPDATE SET
                tetkik_adi = EXCLUDED.tetkik_adi,
                sonuc = EXCLUDED.sonuc
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'tetkik_adi': clean_string(row.get('Tetkik')),
            'sonuc': clean_string(row.get('Sonuc')),
            'sembol': clean_string(row.get('Sembol'))
        })
        count += 1
    
    print(f"✓ Imported {count} imaging results (goruntuleme_sonuclari)")
    return count

async def import_planlar(session):
    """Import plans from PLAN.CSV"""
    rows = read_csv("PLAN.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0)) if row.get('RecID') else count + 1
        if hasta_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO planlar (id, hasta_id, tarih, tip, aciklama, yapildi, hatirlat)
            VALUES (:id, :hasta_id, :tarih, :tip, :aciklama, :yapildi, :hatirlat)
            ON CONFLICT (id) DO UPDATE SET
                aciklama = EXCLUDED.aciklama
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'tip': clean_string(row.get('Tip')),
            'aciklama': clean_string(row.get('Aciklama')),
            'yapildi': clean_string(row.get('Yapildi')),
            'hatirlat': clean_string(row.get('Hatirlat'))
        })
        count += 1
    
    print(f"✓ Imported {count} plans (planlar)")
    return count

async def import_kurumlar(session):
    """Import institutions from KURUM.CSV"""
    rows = read_csv("KURUM.CSV")
    count = 0
    
    for row in rows:
        rec_id = safe_int(row.get('#', 0))
        ad = clean_string(row.get('Ad'))
        if rec_id == 0 or not ad:
            continue
            
        await session.execute(text("""
            INSERT INTO kurumlar (id, ad, adres, vergi_dairesi, vergi_no, telefon, faks, yetkili, notlar)
            VALUES (:id, :ad, :adres, :vergi_dairesi, :vergi_no, :telefon, :faks, :yetkili, :notlar)
            ON CONFLICT (id) DO UPDATE SET
                ad = EXCLUDED.ad
        """), {
            'id': rec_id,
            'ad': clean_string(row.get('Ad')),
            'adres': clean_string(row.get('Adres')),
            'vergi_dairesi': clean_string(row.get('VergiDairesi')),
            'vergi_no': clean_string(row.get('VergiNo')),
            'telefon': clean_string(row.get('Telefon')),
            'faks': clean_string(row.get('Faks')),
            'yetkili': clean_string(row.get('Yetkili')),
            'notlar': clean_string(row.get('Notlar'))
        })
        count += 1
    
    print(f"✓ Imported {count} institutions (kurumlar)")
    return count

async def import_urodinamiler(session):
    """Import urodynamic results from URODINAMI.CSV"""
    rows = read_csv("URODINAMI.CSV")
    count = 0
    
    for row in rows:
        hasta_id = safe_int(row.get('HastaRecID', 0))
        rec_id = safe_int(row.get('RecID', 0)) if row.get('RecID') else count + 1
        if hasta_id == 0:
            continue
            
        await session.execute(text("""
            INSERT INTO urodinamiler (id, hasta_id, tarih, qmax, average_flow, voided_volume, 
                                     residual_urine, sistometry, bac)
            VALUES (:id, :hasta_id, :tarih, :qmax, :average_flow, :voided_volume,
                    :residual_urine, :sistometry, :bac)
            ON CONFLICT (id) DO UPDATE SET
                qmax = EXCLUDED.qmax
        """), {
            'id': rec_id,
            'hasta_id': hasta_id,
            'tarih': parse_date(row.get('Tarih')),
            'qmax': float(row.get('Qmax', 0)) if row.get('Qmax') else None,
            'average_flow': float(row.get('AvgFlow', 0)) if row.get('AvgFlow') else None,
            'voided_volume': float(row.get('VoidedVol', 0)) if row.get('VoidedVol') else None,
            'residual_urine': float(row.get('ResidualUrine', 0)) if row.get('ResidualUrine') else None,
            'sistometry': clean_string(row.get('Sistometry')),
            'bac': clean_string(row.get('BAC'))
        })
        count += 1
    
    print(f"✓ Imported {count} urodynamic results (urodinamiler)")
    return count

async def import_icd_tanilar(session):
    """Import ICD codes from TICD.CSV"""
    rows = read_csv("TICD.CSV")
    count = 0
    
    for row in rows:
        rec_id = safe_int(row.get('#', 0))
        kodu = clean_string(row.get('Kod'))
        if rec_id == 0 or not kodu:
            continue
            
        await session.execute(text("""
            INSERT INTO icd_tanilar (id, kodu, adi, ust_kodu, aktif, seviye)
            VALUES (:id, :kodu, :adi, :ust_kodu, :aktif, :seviye)
            ON CONFLICT (id) DO UPDATE SET
                kodu = EXCLUDED.kodu,
                adi = EXCLUDED.adi
        """), {
            'id': rec_id,
            'kodu': clean_string(row.get('Kod')),
            'adi': clean_string(row.get('Ad')),
            'ust_kodu': clean_string(row.get('UstKod')),
            'aktif': clean_string(row.get('Aktif')),
            'seviye': clean_string(row.get('Seviye'))
        })
        count += 1
    
    print(f"✓ Imported {count} ICD codes (icd_tanilar)")
    return count

async def update_sequences(session):
    """Update PostgreSQL sequences after import"""
    tables = ['hastalar', 'muayeneler', 'operasyonlar', 'sperm_analizleri', 
              'idrar_tahlilleri', 'goruntuleme_sonuclari', 'planlar', 
              'kurumlar', 'urodinamiler', 'icd_tanilar', 'anamnezler']
    
    for table in tables:
        try:
            await session.execute(text(f"""
                SELECT setval(pg_get_serial_sequence('{table}', 'id'), 
                              COALESCE((SELECT MAX(id) FROM {table}), 1))
            """))
        except Exception as e:
            print(f"  Warning: Could not update sequence for {table}: {e}")
    
    print("✓ Updated all sequences")

async def main():
    print("=" * 60)
    print("UroLOG EMR - CSV Import Script")
    print("=" * 60)
    print(f"CSV Directory: {CSV_DIR}")
    print(f"Target DB: urolog_db")
    print("=" * 60)
    
    engine = create_async_engine(DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as session:
        try:
            # Import in order (parent tables first)
            await import_hastalar(session)
            await import_anamnezler(session)
            await import_muayeneler(session)
            await import_operasyonlar(session)
            await import_sperm_analizleri(session)
            await import_idrar_tahlilleri(session)
            await import_goruntuleme(session)
            await import_planlar(session)
            await import_kurumlar(session)
            await import_urodinamiler(session)
            await import_icd_tanilar(session)
            
            # Update sequences
            await update_sequences(session)
            
            await session.commit()
            print("=" * 60)
            print("✅ Import completed successfully!")
            print("=" * 60)
            
        except Exception as e:
            await session.rollback()
            print(f"❌ Error during import: {e}")
            raise
    
    await engine.dispose()

if __name__ == "__main__":
    asyncio.run(main())
