import asyncio
import csv
import sys
import os
from datetime import datetime
from sqlalchemy import text

# Add project root to path
sys.path.append(os.getcwd())

from app.db.session import SessionLocal

CSV_PATH = "/Users/alp/Library/CloudStorage/GoogleDrive-alpozkan@gmail.com/My Drive/AntiGravity/UroLOG_v1.1/03.db_import/csv_exports/GLABIST.CSV"

def parse_date(date_str):
    if not date_str:
        return None
    try:
        # Example format: 10/20/2025
        return datetime.strptime(date_str, "%m/%d/%Y").date()
    except ValueError:
        try:
             # Try DD/MM/YYYY just in case
            return datetime.strptime(date_str, "%d/%m/%Y").date()
        except ValueError:
            return None

async def import_data():
    async with SessionLocal() as db:
        print(f"Reading CSV from: {CSV_PATH}")
        
        try:
            # Try utf-8 first, then different encodings if it fails
            encodings = ['utf-8', 'iso-8859-9', 'windows-1254', 'latin-1']
            rows = []
            
            for enc in encodings:
                try:
                    with open(CSV_PATH, mode='r', encoding=enc) as f:
                        # Skip header lines if they are not standard CSV headers (DBISAM header lines)
                        # We see: Generated by... then newline then "header"
                        # Actually we can just sniff or handle it manually.
                        
                        lines = f.readlines()
                        
                        start_idx = 0
                        for i, line in enumerate(lines):
                            if '"HastaRecID"' in line:
                                start_idx = i
                                break
                        
                        # Process from header
                        reader = csv.DictReader(lines[start_idx:])
                        rows = list(reader)
                        print(f"Successfully read with encoding: {enc}")
                        break
                except UnicodeDecodeError:
                    continue
                except Exception as e:
                    print(f"Error reading with {enc}: {e}")
                    continue
            
            if not rows:
                print("Could not read any rows from CSV.")
                return

            print(f"Found {len(rows)} rows to process.")
            
            count = 0
            for row in rows:
                hasta_rec_id = row.get("HastaRecID")
                if not hasta_rec_id:
                    continue
                
                # Check if patient exists (optional, but good for integrity)
                # skipping Check for performance/simplicity, assuming IDs exist or we want to import anyway
                # But wait, foreign key constraint might fail if patient doesn't exist.
                # Let's try to insert.
                
                tarih_str = row.get("Tarih")
                tarih_val = parse_date(tarih_str)
                
                tetkik_adi = row.get("Tetkik")
                sonuc = row.get("Sonuc")
                sembol = row.get("Sembol")
                
                # Clean strings
                if tetkik_adi: tetkik_adi = tetkik_adi.strip()
                if sonuc: sonuc = sonuc.strip()
                if sembol: sembol = sembol.strip()

                # Insert SQL
                # We use raw sql for simplicity in script, avoiding full schema checks for now
                query = text("""
                    INSERT INTO goruntuleme_sonuclari (hasta_id, tarih, tetkik_adi, sonuc, sembol, created_at)
                    VALUES (:hasta_id, :tarih, :tetkik_adi, :sonuc, :sembol, NOW())
                """)
                
                try:
                    await db.execute(query, {
                        "hasta_id": int(hasta_rec_id),
                        "tarih": tarih_val,
                        "tetkik_adi": tetkik_adi,
                        "sonuc": sonuc,
                        "sembol": sembol
                    })
                    count += 1
                except Exception as e:
                    print(f"Error inserting row {row}: {e}")
            
            await db.commit()
            print(f"Successfully imported {count} records into 'goruntuleme_sonuclari'.")

        except Exception as e:
            print(f"Critical Error: {e}")

if __name__ == "__main__":
    asyncio.run(import_data())
