"""Add kan_sulandirici to Muayene

Revision ID: 02b317236b70
Revises: f1cd7bfbf6a2
Create Date: 2025-12-23 16:36:59.538402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b317236b70'
down_revision: Union[str, None] = 'f1cd7bfbf6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muayeneler', sa.Column('kan_sulandirici', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muayeneler', 'kan_sulandirici')
    # ### end Alembic commands ###
