"""Add Visual fields to Hasta

Revision ID: 207fdeaa017b
Revises: a3ab1eb8f336
Create Date: 2025-12-25 22:38:34.922464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207fdeaa017b'
down_revision: Union[str, None] = 'a3ab1eb8f336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), 'durum_bildirir_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_durum_bildirir_raporlari_tarih'), 'durum_bildirir_raporlari', ['tarih'], unique=False)
    op.create_index(op.f('ix_fotograf_arsivi_hasta_id'), 'fotograf_arsivi', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_fotograf_arsivi_tarih'), 'fotograf_arsivi', ['tarih'], unique=False)
    op.create_index(op.f('ix_hasta_finans_hareketleri_hasta_id'), 'hasta_finans_hareketleri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_hasta_finans_hareketleri_tarih'), 'hasta_finans_hareketleri', ['tarih'], unique=False)
    op.create_index(op.f('ix_hasta_notlari_hasta_id'), 'hasta_notlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_hasta_notlari_tarih'), 'hasta_notlari', ['tarih'], unique=False)
    op.add_column('hastalar', sa.Column('sms_izin', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('email_izin', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('iletisim_kaynagi', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('iletisim_tercihi', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('indirim_grubu', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('dil', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('personel_ids', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('etiketler', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('kayit_notu', sa.Text(), nullable=True))
    op.create_index(op.f('ix_istirahat_raporlari_hasta_id'), 'istirahat_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_istirahat_raporlari_tarih'), 'istirahat_raporlari', ['tarih'], unique=False)
    op.create_index(op.f('ix_muayeneler_hasta_id'), 'muayeneler', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_muayeneler_tarih'), 'muayeneler', ['tarih'], unique=False)
    op.drop_column('muayeneler', 'tedavi_plani')
    op.drop_column('muayeneler', 'takip_notu')
    op.create_index(op.f('ix_operasyonlar_hasta_id'), 'operasyonlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_operasyonlar_tarih'), 'operasyonlar', ['tarih'], unique=False)
    op.create_index(op.f('ix_planlar_hasta_id'), 'planlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_planlar_tarih'), 'planlar', ['tarih'], unique=False)
    op.alter_column('randevular', 'hasta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_randevular_google_event_id'), table_name='randevular')
    op.drop_column('randevular', 'last_synced_at')
    op.drop_column('randevular', 'google_event_id')
    op.create_index(op.f('ix_telefon_gorusmeleri_hasta_id'), 'telefon_gorusmeleri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_telefon_gorusmeleri_tarih'), 'telefon_gorusmeleri', ['tarih'], unique=False)
    op.create_index(op.f('ix_tetkik_sonuclari_hasta_id'), 'tetkik_sonuclari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tetkik_sonuclari_tarih'), 'tetkik_sonuclari', ['tarih'], unique=False)
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), 'tibbi_mudahale_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_tarih'), 'tibbi_mudahale_raporlari', ['tarih'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_tarih'), table_name='tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tetkik_sonuclari_tarih'), table_name='tetkik_sonuclari')
    op.drop_index(op.f('ix_tetkik_sonuclari_hasta_id'), table_name='tetkik_sonuclari')
    op.drop_index(op.f('ix_telefon_gorusmeleri_tarih'), table_name='telefon_gorusmeleri')
    op.drop_index(op.f('ix_telefon_gorusmeleri_hasta_id'), table_name='telefon_gorusmeleri')
    op.add_column('randevular', sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('randevular', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_randevular_google_event_id'), 'randevular', ['google_event_id'], unique=False)
    op.alter_column('randevular', 'hasta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_planlar_tarih'), table_name='planlar')
    op.drop_index(op.f('ix_planlar_hasta_id'), table_name='planlar')
    op.drop_index(op.f('ix_operasyonlar_tarih'), table_name='operasyonlar')
    op.drop_index(op.f('ix_operasyonlar_hasta_id'), table_name='operasyonlar')
    op.add_column('muayeneler', sa.Column('takip_notu', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('muayeneler', sa.Column('tedavi_plani', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_muayeneler_tarih'), table_name='muayeneler')
    op.drop_index(op.f('ix_muayeneler_hasta_id'), table_name='muayeneler')
    op.drop_index(op.f('ix_istirahat_raporlari_tarih'), table_name='istirahat_raporlari')
    op.drop_index(op.f('ix_istirahat_raporlari_hasta_id'), table_name='istirahat_raporlari')
    op.drop_column('hastalar', 'kayit_notu')
    op.drop_column('hastalar', 'etiketler')
    op.drop_column('hastalar', 'personel_ids')
    op.drop_column('hastalar', 'dil')
    op.drop_column('hastalar', 'indirim_grubu')
    op.drop_column('hastalar', 'iletisim_tercihi')
    op.drop_column('hastalar', 'iletisim_kaynagi')
    op.drop_column('hastalar', 'email_izin')
    op.drop_column('hastalar', 'sms_izin')
    op.drop_index(op.f('ix_hasta_notlari_tarih'), table_name='hasta_notlari')
    op.drop_index(op.f('ix_hasta_notlari_hasta_id'), table_name='hasta_notlari')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_tarih'), table_name='hasta_finans_hareketleri')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_hasta_id'), table_name='hasta_finans_hareketleri')
    op.drop_index(op.f('ix_fotograf_arsivi_tarih'), table_name='fotograf_arsivi')
    op.drop_index(op.f('ix_fotograf_arsivi_hasta_id'), table_name='fotograf_arsivi')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_tarih'), table_name='durum_bildirir_raporlari')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), table_name='durum_bildirir_raporlari')
    # ### end Alembic commands ###
