"""Add Protokol No

Revision ID: 25936d7f3371
Revises: 207fdeaa017b
Create Date: 2025-12-25 23:07:07.725032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25936d7f3371'
down_revision: Union[str, None] = '207fdeaa017b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hastalar', sa.Column('protokol_no', sa.String(), nullable=True))
    op.create_index(op.f('ix_hastalar_protokol_no'), 'hastalar', ['protokol_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hastalar_protokol_no'), table_name='hastalar')
    op.drop_column('hastalar', 'protokol_no')
    # ### end Alembic commands ###
