"""Add IstirahatRaporu table

Revision ID: 2f9032543018
Revises: c4b5d9d345ce
Create Date: 2025-12-22 00:09:37.765034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9032543018'
down_revision: Union[str, None] = 'c4b5d9d345ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('istirahat_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('icd_kodu', sa.String(), nullable=True),
    sa.Column('tani', sa.Text(), nullable=True),
    sa.Column('karar', sa.String(), nullable=True),
    sa.Column('kontrol_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_istirahat_raporlari_id'), 'istirahat_raporlari', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_istirahat_raporlari_id'), table_name='istirahat_raporlari')
    op.drop_table('istirahat_raporlari')
    # ### end Alembic commands ###
