"""add_ilac_tanim_table

Revision ID: 41fced6c0561
Revises: b80407e65704
Create Date: 2025-12-28 21:07:46.456737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fced6c0561'
down_revision: Union[str, None] = 'b80407e65704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ilac_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('etkin_madde', sa.String(), nullable=True),
    sa.Column('atc_kodu', sa.String(), nullable=True),
    sa.Column('fiyat', sa.String(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('recete_tipi', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ilac_tanimlari_barcode'), 'ilac_tanimlari', ['barcode'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_id'), 'ilac_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_name'), 'ilac_tanimlari', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ilac_tanimlari_name'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_id'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_barcode'), table_name='ilac_tanimlari')
    op.drop_table('ilac_tanimlari')
    # ### end Alembic commands ###
