"""Add missing clinical columns

Revision ID: 484cbbddd67e
Revises: 717404b77cd5
Create Date: 2025-12-13 14:56:30.561480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484cbbddd67e'
down_revision: Union[str, None] = '717404b77cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muayeneler', sa.Column('sistem_sorgu', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('ipss_skor', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('fizik_muayene', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muayeneler', 'fizik_muayene')
    op.drop_column('muayeneler', 'ipss_skor')
    op.drop_column('muayeneler', 'sistem_sorgu')
    # ### end Alembic commands ###
