"""Initial schema

Revision ID: 538a7c00d836
Revises: 
Create Date: 2025-12-08 21:42:00.167439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538a7c00d836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekip_uyeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(), nullable=False),
    sa.Column('gorev', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ekip_uyeleri_id'), 'ekip_uyeleri', ['id'], unique=False)
    op.create_table('hastalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tc_kimlik', sa.String(), nullable=True),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('soyad', sa.String(), nullable=True),
    sa.Column('cinsiyet', sa.String(), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('dogum_yeri', sa.String(), nullable=True),
    sa.Column('kan_grubu', sa.String(), nullable=True),
    sa.Column('medeni_hal', sa.String(), nullable=True),
    sa.Column('meslek', sa.String(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('ev_tel', sa.String(), nullable=True),
    sa.Column('is_tel', sa.String(), nullable=True),
    sa.Column('cep_tel', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('kimlik_notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hastalar_ad'), 'hastalar', ['ad'], unique=False)
    op.create_index(op.f('ix_hastalar_id'), 'hastalar', ['id'], unique=False)
    op.create_index(op.f('ix_hastalar_soyad'), 'hastalar', ['soyad'], unique=False)
    op.create_index(op.f('ix_hastalar_tc_kimlik'), 'hastalar', ['tc_kimlik'], unique=True)
    op.create_table('hizmet_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('fiyat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hizmet_tanimlari_id'), 'hizmet_tanimlari', ['id'], unique=False)
    op.create_table('icd_tanilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kodu', sa.String(), nullable=False),
    sa.Column('adi', sa.String(), nullable=True),
    sa.Column('ust_kodu', sa.String(), nullable=True),
    sa.Column('aktif', sa.String(), nullable=True),
    sa.Column('seviye', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd_tanilar_adi'), 'icd_tanilar', ['adi'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_id'), 'icd_tanilar', ['id'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_kodu'), 'icd_tanilar', ['kodu'], unique=True)
    op.create_table('kurumlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('vergi_dairesi', sa.String(), nullable=True),
    sa.Column('vergi_no', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('faks', sa.String(), nullable=True),
    sa.Column('yetkili', sa.String(), nullable=True),
    sa.Column('notlar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurumlar_id'), 'kurumlar', ['id'], unique=False)
    op.create_table('sablon_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup', sa.String(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('icerik', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sablon_tanimlari_grup'), 'sablon_tanimlari', ['grup'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_id'), 'sablon_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_kod'), 'sablon_tanimlari', ['kod'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anamnezler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('alkol', sa.String(), nullable=True),
    sa.Column('sigara', sa.String(), nullable=True),
    sa.Column('allerji', sa.Text(), nullable=True),
    sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('soygecmis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hasta_id')
    )
    op.create_index(op.f('ix_anamnezler_id'), 'anamnezler', ['id'], unique=False)
    op.create_table('genel_lab_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('referans_araligi', sa.String(), nullable=True),
    sa.Column('bayrak', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genel_lab_sonuclari_id'), 'genel_lab_sonuclari', ['id'], unique=False)
    op.create_table('goruntuleme_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goruntuleme_sonuclari_id'), 'goruntuleme_sonuclari', ['id'], unique=False)
    op.create_table('hasta_dosyalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dosya_tipi', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('legacy_data', sa.LargeBinary(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('arsiv_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_dosyalari_id'), 'hasta_dosyalari', ['id'], unique=False)
    op.create_table('hasta_finans_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_tipi', sa.String(), nullable=False),
    sa.Column('hizmet_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(), nullable=True),
    sa.Column('borc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('alacak', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bakiye', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.ForeignKeyConstraint(['hizmet_id'], ['hizmet_tanimlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_finans_hareketleri_id'), 'hasta_finans_hareketleri', ['id'], unique=False)
    op.create_table('hasta_notlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_notlari_id'), 'hasta_notlari', ['id'], unique=False)
    op.create_table('idrar_tahlilleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dansite', sa.String(), nullable=True),
    sa.Column('ph', sa.String(), nullable=True),
    sa.Column('sediment', sa.Text(), nullable=True),
    sa.Column('steril', sa.String(), nullable=True),
    sa.Column('koloni', sa.String(), nullable=True),
    sa.Column('bakteri', sa.String(), nullable=True),
    sa.Column('antibiyogram', sa.Text(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idrar_tahlilleri_id'), 'idrar_tahlilleri', ['id'], unique=False)
    op.create_table('muayeneler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('sikayet', sa.Text(), nullable=True),
    sa.Column('oyku', sa.Text(), nullable=True),
    sa.Column('tansiyon', sa.String(), nullable=True),
    sa.Column('ates', sa.String(), nullable=True),
    sa.Column('kvah', sa.String(), nullable=True),
    sa.Column('bobrek_sag', sa.String(), nullable=True),
    sa.Column('bobrek_sol', sa.String(), nullable=True),
    sa.Column('suprapubik_kitle', sa.String(), nullable=True),
    sa.Column('ego', sa.String(), nullable=True),
    sa.Column('rektal_tuse', sa.String(), nullable=True),
    sa.Column('disuri', sa.String(), nullable=True),
    sa.Column('pollakiuri', sa.String(), nullable=True),
    sa.Column('nokturi', sa.String(), nullable=True),
    sa.Column('hematuri', sa.String(), nullable=True),
    sa.Column('genital_akinti', sa.String(), nullable=True),
    sa.Column('kabizlik', sa.String(), nullable=True),
    sa.Column('tas_oyku', sa.String(), nullable=True),
    sa.Column('catallanma', sa.String(), nullable=True),
    sa.Column('projeksiyon_azalma', sa.String(), nullable=True),
    sa.Column('kalibre_incelme', sa.String(), nullable=True),
    sa.Column('idrar_bas_zorluk', sa.String(), nullable=True),
    sa.Column('kesik_idrar_yapma', sa.String(), nullable=True),
    sa.Column('terminal_damlama', sa.String(), nullable=True),
    sa.Column('residiv_hissi', sa.String(), nullable=True),
    sa.Column('inkontinans', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muayeneler_id'), 'muayeneler', ['id'], unique=False)
    op.create_table('operasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('ameliyat', sa.String(), nullable=True),
    sa.Column('pre_op_tani', sa.String(), nullable=True),
    sa.Column('post_op_tani', sa.String(), nullable=True),
    sa.Column('ekip', sa.Text(), nullable=True),
    sa.Column('hemsire', sa.String(), nullable=True),
    sa.Column('anestezi_ekip', sa.String(), nullable=True),
    sa.Column('anestezi_tur', sa.String(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('patoloji', sa.Text(), nullable=True),
    sa.Column('post_op', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operasyonlar_id'), 'operasyonlar', ['id'], unique=False)
    op.create_table('planlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('yapildi', sa.String(), nullable=True),
    sa.Column('hatirlat', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planlar_id'), 'planlar', ['id'], unique=False)
    op.create_table('sperm_analizleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('perhiz', sa.String(), nullable=True),
    sa.Column('volum', sa.String(), nullable=True),
    sa.Column('likefaksiyon', sa.String(), nullable=True),
    sa.Column('viskozite', sa.String(), nullable=True),
    sa.Column('aglutinasyon', sa.String(), nullable=True),
    sa.Column('yuvarlak_hucre', sa.String(), nullable=True),
    sa.Column('sayi', sa.String(), nullable=True),
    sa.Column('motilite', sa.String(), nullable=True),
    sa.Column('p_motilite', sa.String(), nullable=True),
    sa.Column('tpmss', sa.String(), nullable=True),
    sa.Column('kruger', sa.String(), nullable=True),
    sa.Column('metod', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sperm_analizleri_id'), 'sperm_analizleri', ['id'], unique=False)
    op.create_table('urodinamiler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('qmax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_flow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voided_volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('residual_urine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sistometry', sa.Text(), nullable=True),
    sa.Column('bac', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urodinamiler_id'), 'urodinamiler', ['id'], unique=False)
    op.create_table('telefon_gorusmeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefon_gorusmeleri_id'), 'telefon_gorusmeleri', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urodinamiler_id'), table_name='urodinamiler')
    op.drop_table('urodinamiler')
    op.drop_index(op.f('ix_sperm_analizleri_id'), table_name='sperm_analizleri')
    op.drop_table('sperm_analizleri')
    op.drop_index(op.f('ix_planlar_id'), table_name='planlar')
    op.drop_table('planlar')
    op.drop_index(op.f('ix_operasyonlar_id'), table_name='operasyonlar')
    op.drop_table('operasyonlar')
    op.drop_index(op.f('ix_muayeneler_id'), table_name='muayeneler')
    op.drop_table('muayeneler')
    op.drop_index(op.f('ix_idrar_tahlilleri_id'), table_name='idrar_tahlilleri')
    op.drop_table('idrar_tahlilleri')
    op.drop_index(op.f('ix_hasta_notlari_id'), table_name='hasta_notlari')
    op.drop_table('hasta_notlari')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_id'), table_name='hasta_finans_hareketleri')
    op.drop_table('hasta_finans_hareketleri')
    op.drop_index(op.f('ix_hasta_dosyalari_id'), table_name='hasta_dosyalari')
    op.drop_table('hasta_dosyalari')
    op.drop_index(op.f('ix_goruntuleme_sonuclari_id'), table_name='goruntuleme_sonuclari')
    op.drop_table('goruntuleme_sonuclari')
    op.drop_index(op.f('ix_genel_lab_sonuclari_id'), table_name='genel_lab_sonuclari')
    op.drop_table('genel_lab_sonuclari')
    op.drop_index(op.f('ix_anamnezler_id'), table_name='anamnezler')
    op.drop_table('anamnezler')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sablon_tanimlari_kod'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_id'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_grup'), table_name='sablon_tanimlari')
    op.drop_table('sablon_tanimlari')
    op.drop_index(op.f('ix_kurumlar_id'), table_name='kurumlar')
    op.drop_table('kurumlar')
    op.drop_index(op.f('ix_icd_tanilar_kodu'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_id'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_adi'), table_name='icd_tanilar')
    op.drop_table('icd_tanilar')
    op.drop_index(op.f('ix_hizmet_tanimlari_id'), table_name='hizmet_tanimlari')
    op.drop_table('hizmet_tanimlari')
    op.drop_index(op.f('ix_hastalar_tc_kimlik'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_soyad'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_id'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_ad'), table_name='hastalar')
    op.drop_table('hastalar')
    op.drop_index(op.f('ix_ekip_uyeleri_id'), table_name='ekip_uyeleri')
    op.drop_table('ekip_uyeleri')
    # ### end Alembic commands ###
