"""Add_finance_module

Revision ID: 64a0c68a2040
Revises: edf0c1f424bd
Create Date: 2025-12-20 10:55:22.478279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a0c68a2040'
down_revision: Union[str, None] = 'edf0c1f424bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kasa_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('para_birimi', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasa_tanimlari_id'), 'kasa_tanimlari', ['id'], unique=False)
    op.add_column('hasta_finans_hareketleri', sa.Column('kasa_id', sa.Integer(), nullable=True))
    op.add_column('hasta_finans_hareketleri', sa.Column('odeme_yontemi', sa.String(), nullable=True))
    op.create_foreign_key(None, 'hasta_finans_hareketleri', 'kasa_tanimlari', ['kasa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='foreignkey')
    op.drop_column('hasta_finans_hareketleri', 'odeme_yontemi')
    op.drop_column('hasta_finans_hareketleri', 'kasa_id')
    op.drop_index(op.f('ix_kasa_tanimlari_id'), table_name='kasa_tanimlari')
    op.drop_table('kasa_tanimlari')
    # ### end Alembic commands ###
