"""revert_db_schema_to_standard_ids

Revision ID: 717404b77cd5
Revises: e43f79b9aaa6
Create Date: 2025-12-13 14:17:59.916711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717404b77cd5'
down_revision: Union[str, None] = 'e43f79b9aaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'urodinamiler', type_='foreignkey')
    op.create_foreign_key(op.f('urodinamiler_hasta_id_fkey'), 'urodinamiler', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.drop_constraint(None, 'sperm_analizleri', type_='foreignkey')
    op.create_foreign_key(op.f('sperm_analizleri_hasta_id_fkey'), 'sperm_analizleri', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.add_column('randevular', sa.Column('hasta_rec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'randevular', type_='foreignkey')
    op.create_foreign_key(op.f('randevular_hasta_id_fkey'), 'randevular', 'hastalar', ['hasta_rec_id'], ['hasta_rec_id'])
    op.drop_index(op.f('ix_randevular_hasta_id'), table_name='randevular')
    op.create_index(op.f('ix_randevular_hasta_id'), 'randevular', ['hasta_rec_id'], unique=False)
    op.drop_column('randevular', 'hasta_id')
    op.drop_constraint(None, 'planlar', type_='foreignkey')
    op.create_foreign_key(op.f('planlar_hasta_id_fkey'), 'planlar', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.add_column('operasyonlar', sa.Column('hasta_rec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('operasyonlar', sa.Column('rec_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'operasyonlar', type_='foreignkey')
    op.create_foreign_key(op.f('operasyonlar_hasta_id_fkey'), 'operasyonlar', 'hastalar', ['hasta_rec_id'], ['hasta_rec_id'])
    op.drop_index(op.f('ix_operasyonlar_id'), table_name='operasyonlar')
    op.create_index(op.f('ix_operasyonlar_id'), 'operasyonlar', ['rec_id'], unique=False)
    op.drop_column('operasyonlar', 'hasta_id')
    op.drop_column('operasyonlar', 'id')
    op.add_column('muayeneler', sa.Column('hasta_rec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('muayeneler', sa.Column('m_rec_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'muayeneler', type_='foreignkey')
    op.create_foreign_key(op.f('muayeneler_hasta_id_fkey'), 'muayeneler', 'hastalar', ['hasta_rec_id'], ['hasta_rec_id'])
    op.drop_index(op.f('ix_muayeneler_id'), table_name='muayeneler')
    op.create_index(op.f('ix_muayeneler_id'), 'muayeneler', ['m_rec_id'], unique=False)
    op.alter_column('muayeneler', 'tedavi',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('muayeneler', 'oneriler',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('muayeneler', 'hasta_id')
    op.drop_column('muayeneler', 'id')
    op.drop_constraint(None, 'idrar_tahlilleri', type_='foreignkey')
    op.create_foreign_key(op.f('idrar_tahlilleri_hasta_id_fkey'), 'idrar_tahlilleri', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.add_column('hastalar', sa.Column('hasta_rec_id', sa.INTEGER(), server_default=sa.text("nextval('hastalar_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_hastalar_id'), table_name='hastalar')
    op.create_index(op.f('ix_hastalar_id'), 'hastalar', ['hasta_rec_id'], unique=False)
    op.drop_column('hastalar', 'id')
    op.add_column('hasta_notlari', sa.Column('hasta_rec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hasta_notlari', type_='foreignkey')
    op.create_foreign_key(op.f('hasta_notlari_hasta_id_fkey'), 'hasta_notlari', 'hastalar', ['hasta_rec_id'], ['hasta_rec_id'])
    op.drop_column('hasta_notlari', 'hasta_id')
    op.add_column('hasta_finans_hareketleri', sa.Column('hasta_rec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='foreignkey')
    op.create_foreign_key(op.f('hasta_finans_hareketleri_hasta_id_fkey'), 'hasta_finans_hareketleri', 'hastalar', ['hasta_rec_id'], ['hasta_rec_id'])
    op.drop_column('hasta_finans_hareketleri', 'hasta_id')
    op.drop_constraint(None, 'hasta_dosyalari', type_='foreignkey')
    op.create_foreign_key(op.f('hasta_dosyalari_hasta_id_fkey'), 'hasta_dosyalari', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.drop_constraint(None, 'goruntuleme_sonuclari', type_='foreignkey')
    op.create_foreign_key(op.f('goruntuleme_sonuclari_hasta_id_fkey'), 'goruntuleme_sonuclari', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.drop_constraint(None, 'genel_lab_sonuclari', type_='foreignkey')
    op.create_foreign_key(op.f('genel_lab_sonuclari_hasta_id_fkey'), 'genel_lab_sonuclari', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    op.drop_constraint(None, 'anamnezler', type_='foreignkey')
    op.create_foreign_key(op.f('anamnezler_hasta_id_fkey'), 'anamnezler', 'hastalar', ['hasta_id'], ['hasta_rec_id'])
    # ### end Alembic commands ###
