"""Add missing randevular table

Revision ID: 78e96316c3f1
Revises: ea128d86d867
Create Date: 2025-12-14 12:22:51.748693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e96316c3f1'
down_revision: Union[str, None] = 'ea128d86d867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('randevular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randevular_hasta_id'), 'randevular', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_randevular_id'), 'randevular', ['id'], unique=False)
    op.create_index(op.f('ix_randevular_start'), 'randevular', ['start'], unique=False)
    op.add_column('muayeneler', sa.Column('tani1', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('tani2', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('oneriler', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('tedavi', sa.Text(), nullable=True))
    op.drop_column('muayeneler', 'sistem_sorgu')
    op.drop_column('muayeneler', 'ipss_skor')
    op.drop_column('muayeneler', 'fizik_muayene')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'email')
    op.add_column('muayeneler', sa.Column('fizik_muayene', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('muayeneler', sa.Column('ipss_skor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('muayeneler', sa.Column('sistem_sorgu', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('muayeneler', 'tedavi')
    op.drop_column('muayeneler', 'oneriler')
    op.drop_column('muayeneler', 'tani2')
    op.drop_column('muayeneler', 'tani1')
    op.drop_index(op.f('ix_randevular_start'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_id'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_hasta_id'), table_name='randevular')
    op.drop_table('randevular')
    # ### end Alembic commands ###
