"""Add google calendar and oauth fields

Revision ID: a3ab1eb8f336
Revises: 8bd2250c67fa
Create Date: 2025-12-25 09:22:38.713655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ab1eb8f336'
down_revision: Union[str, None] = '8bd2250c67fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.add_column('randevular', sa.Column('google_event_id', sa.String(), nullable=True))
    op.add_column('randevular', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_randevular_google_event_id'), 'randevular', ['google_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_randevular_google_event_id'), table_name='randevular')
    op.drop_column('randevular', 'last_synced_at')
    op.drop_column('randevular', 'google_event_id')
    op.drop_table('user_oauth')
    # ### end Alembic commands ###
