"""add_iief_ef_fields

Revision ID: b80407e65704
Revises: e6b4182635f9
Create Date: 2025-12-28 13:00:57.717318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80407e65704'
down_revision: Union[str, None] = 'e6b4182635f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hastalar_protokol_no'), table_name='hastalar')
    op.create_index(op.f('ix_hastalar_protokol_no'), 'hastalar', ['protokol_no'], unique=False)
    op.add_column('muayeneler', sa.Column('iief_ef_skor', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('iief_ef_answers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muayeneler', 'iief_ef_answers')
    op.drop_column('muayeneler', 'iief_ef_skor')
    op.drop_index(op.f('ix_hastalar_protokol_no'), table_name='hastalar')
    op.create_index(op.f('ix_hastalar_protokol_no'), 'hastalar', ['protokol_no'], unique=True)
    # ### end Alembic commands ###
