"""add_missing_patient_columns

Revision ID: c4b5d9d345ce
Revises: 64a0c68a2040
Create Date: 2025-12-21 00:14:38.329650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b5d9d345ce'
down_revision: Union[str, None] = '64a0c68a2040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('tetkik_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('referans_araligi', sa.String(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tetkik_sonuclari_id'), 'tetkik_sonuclari', ['id'], unique=False)
    op.add_column('hasta_dosyalari', sa.Column('etiketler', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('referans', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('postakodu', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('kurum', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('sigorta', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('ozelsigorta', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('cocuk_sayisi', sa.String(), nullable=True))
    op.add_column('hastalar', sa.Column('faks', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('tani1_kodu', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('tani2_kodu', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('sonuc', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('prosedur', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('doktor', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('bulgu_notu', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('recete', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('erektil_islev', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('ejakulasyon', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('mshq', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('ozgecmis', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('soygecmis', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('aliskanliklar', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('sistem_sorgu', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('ipss_skor', sa.String(), nullable=True))
    op.add_column('muayeneler', sa.Column('fizik_muayene', sa.Text(), nullable=True))
    op.add_column('muayeneler', sa.Column('allerjiler', sa.Text(), nullable=True))
    op.add_column('randevular', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'randevular', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'urodinamiler', 'hastalar', ['hasta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urodinamiler', type_='foreignkey')
    op.drop_constraint(None, 'randevular', type_='foreignkey')
    op.drop_column('randevular', 'doctor_id')
    op.drop_column('muayeneler', 'allerjiler')
    op.drop_column('muayeneler', 'fizik_muayene')
    op.drop_column('muayeneler', 'ipss_skor')
    op.drop_column('muayeneler', 'sistem_sorgu')
    op.drop_column('muayeneler', 'aliskanliklar')
    op.drop_column('muayeneler', 'kullandigi_ilaclar')
    op.drop_column('muayeneler', 'soygecmis')
    op.drop_column('muayeneler', 'ozgecmis')
    op.drop_column('muayeneler', 'mshq')
    op.drop_column('muayeneler', 'ejakulasyon')
    op.drop_column('muayeneler', 'erektil_islev')
    op.drop_column('muayeneler', 'recete')
    op.drop_column('muayeneler', 'bulgu_notu')
    op.drop_column('muayeneler', 'doktor')
    op.drop_column('muayeneler', 'prosedur')
    op.drop_column('muayeneler', 'sonuc')
    op.drop_column('muayeneler', 'tani2_kodu')
    op.drop_column('muayeneler', 'tani1_kodu')
    op.drop_column('hastalar', 'faks')
    op.drop_column('hastalar', 'cocuk_sayisi')
    op.drop_column('hastalar', 'ozelsigorta')
    op.drop_column('hastalar', 'sigorta')
    op.drop_column('hastalar', 'kurum')
    op.drop_column('hastalar', 'postakodu')
    op.drop_column('hastalar', 'referans')
    op.drop_column('hasta_dosyalari', 'etiketler')
    op.drop_index(op.f('ix_tetkik_sonuclari_id'), table_name='tetkik_sonuclari')
    op.drop_table('tetkik_sonuclari')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
