"""Add fotograf_arsivi table try 4

Revision ID: ea128d86d867
Revises: 484cbbddd67e
Create Date: 2025-12-13 20:36:55.516151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea128d86d867'
down_revision: Union[str, None] = '484cbbddd67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotograf_arsivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('asama', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotograf_arsivi_id'), 'fotograf_arsivi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fotograf_arsivi_id'), table_name='fotograf_arsivi')
    op.drop_table('fotograf_arsivi')
    # ### end Alembic commands ###
