"""Add LabUroflowmetri

Revision ID: edf0c1f424bd
Revises: 78e96316c3f1
Create Date: 2025-12-20 00:49:16.655151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf0c1f424bd'
down_revision: Union[str, None] = '78e96316c3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_uroflowmetri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('qmax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_flow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('residual_urine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_uroflowmetri_id'), 'lab_uroflowmetri', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_uroflowmetri_id'), table_name='lab_uroflowmetri')
    op.drop_table('lab_uroflowmetri')
    # ### end Alembic commands ###
