"""Add appointment deletion and cancellation fields

Revision ID: f1cd7bfbf6a2
Revises: f5b9a6db255d
Create Date: 2025-12-23 11:27:07.343489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cd7bfbf6a2'
down_revision: Union[str, None] = 'f5b9a6db255d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('durum_bildirir_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tani_bulgular', sa.Text(), nullable=True),
    sa.Column('icd_kodu', sa.String(), nullable=True),
    sa.Column('sonuc_kanaat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_durum_bildirir_raporlari_id'), 'durum_bildirir_raporlari', ['id'], unique=False)
    op.create_table('tibbi_mudahale_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_basligi', sa.String(), nullable=True),
    sa.Column('islem_detayi', sa.Text(), nullable=True),
    sa.Column('sonuc_oneriler', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_id'), 'tibbi_mudahale_raporlari', ['id'], unique=False)
    op.add_column('randevular', sa.Column('is_deleted', sa.Integer(), nullable=True))
    op.add_column('randevular', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.add_column('randevular', sa.Column('delete_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('randevular', 'delete_reason')
    op.drop_column('randevular', 'cancel_reason')
    op.drop_column('randevular', 'is_deleted')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_table('tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_id'), table_name='durum_bildirir_raporlari')
    op.drop_table('durum_bildirir_raporlari')
    # ### end Alembic commands ###
