"""add etiketler to hasta_notlari

Revision ID: f5b9a6db255d
Revises: 2f9032543018
Create Date: 2025-12-22 11:41:58.418513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b9a6db255d'
down_revision: Union[str, None] = '2f9032543018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasta_notlari', sa.Column('etiketler', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hasta_notlari', 'etiketler')
    # ### end Alembic commands ###
