"""create_initial_sharded_tables

Revision ID: 4bec85e3d165
Revises: 640bf5f2ae8c
Create Date: 2026-01-30 13:53:49.936521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bec85e3d165'
down_revision: Union[str, None] = '640bf5f2ae8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharded_clinical_durum_bildirir_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('tani_bulgular', sa.Text(), nullable=True),
    sa.Column('icd_kodu', sa.String(length=50), nullable=True),
    sa.Column('sonuc_kanaat', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_durum_bildirir_raporlari_hasta_id'), 'sharded_clinical_durum_bildirir_raporlari', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_durum_bildirir_raporlari_id'), 'sharded_clinical_durum_bildirir_raporlari', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_fotograflar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('asama', sa.String(length=50), nullable=True),
    sa.Column('etiketler', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=255), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_fotograflar_hasta_id'), 'sharded_clinical_fotograflar', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_fotograflar_id'), 'sharded_clinical_fotograflar', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_istirahat_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=True),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('icd_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani', sa.Text(), nullable=True),
    sa.Column('karar', sa.String(length=100), nullable=True),
    sa.Column('kontrol_tarihi', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_istirahat_raporlari_hasta_id'), 'sharded_clinical_istirahat_raporlari', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_istirahat_raporlari_id'), 'sharded_clinical_istirahat_raporlari', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_muayeneler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('sikayet', sa.Text(), nullable=True),
    sa.Column('oyku', sa.Text(), nullable=True),
    sa.Column('bulgu_notu', sa.Text(), nullable=True),
    sa.Column('tani1', sa.String(length=255), nullable=True),
    sa.Column('tedavi', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('recete', sa.Text(), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('soygecmis', sa.Text(), nullable=True),
    sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True),
    sa.Column('kan_sulandirici', sa.Integer(), nullable=True),
    sa.Column('aliskanliklar', sa.Text(), nullable=True),
    sa.Column('sistem_sorgu', sa.Text(), nullable=True),
    sa.Column('ipss_skor', sa.String(length=50), nullable=True),
    sa.Column('iief_ef_skor', sa.String(length=50), nullable=True),
    sa.Column('iief_ef_answers', sa.Text(), nullable=True),
    sa.Column('fizik_muayene', sa.Text(), nullable=True),
    sa.Column('erektil_islev', sa.String(length=50), nullable=True),
    sa.Column('ejakulasyon', sa.String(length=50), nullable=True),
    sa.Column('mshq', sa.String(length=50), nullable=True),
    sa.Column('prosedur', sa.Text(), nullable=True),
    sa.Column('allerjiler', sa.Text(), nullable=True),
    sa.Column('tani1_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani2', sa.String(length=255), nullable=True),
    sa.Column('tani2_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani3', sa.String(length=255), nullable=True),
    sa.Column('tani3_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani4', sa.String(length=255), nullable=True),
    sa.Column('tani4_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani5', sa.String(length=255), nullable=True),
    sa.Column('tani5_kodu', sa.String(length=50), nullable=True),
    sa.Column('oneriler', sa.Text(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('tansiyon', sa.String(length=50), nullable=True),
    sa.Column('ates', sa.String(length=50), nullable=True),
    sa.Column('kvah', sa.String(length=50), nullable=True),
    sa.Column('bobrek_sag', sa.String(length=50), nullable=True),
    sa.Column('bobrek_sol', sa.String(length=50), nullable=True),
    sa.Column('suprapubik_kitle', sa.String(length=50), nullable=True),
    sa.Column('ego', sa.String(length=50), nullable=True),
    sa.Column('rektal_tuse', sa.String(length=50), nullable=True),
    sa.Column('disuri', sa.String(length=10), nullable=True),
    sa.Column('pollakiuri', sa.String(length=10), nullable=True),
    sa.Column('nokturi', sa.String(length=10), nullable=True),
    sa.Column('hematuri', sa.String(length=10), nullable=True),
    sa.Column('genital_akinti', sa.String(length=10), nullable=True),
    sa.Column('kabizlik', sa.String(length=10), nullable=True),
    sa.Column('tas_oyku', sa.String(length=10), nullable=True),
    sa.Column('catallanma', sa.String(length=10), nullable=True),
    sa.Column('projeksiyon_azalma', sa.String(length=10), nullable=True),
    sa.Column('kalibre_incelme', sa.String(length=10), nullable=True),
    sa.Column('idrar_bas_zorluk', sa.String(length=10), nullable=True),
    sa.Column('kesik_idrar_yapma', sa.String(length=10), nullable=True),
    sa.Column('terminal_damlama', sa.String(length=10), nullable=True),
    sa.Column('residiv_hissi', sa.String(length=10), nullable=True),
    sa.Column('inkontinans', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_muayeneler_hasta_id'), 'sharded_clinical_muayeneler', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_muayeneler_id'), 'sharded_clinical_muayeneler', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_notlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('tip', sa.String(length=100), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(length=50), nullable=True),
    sa.Column('etiketler', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_notlar_hasta_id'), 'sharded_clinical_notlar', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_notlar_id'), 'sharded_clinical_notlar', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_operasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('ameliyat', sa.String(length=255), nullable=True),
    sa.Column('pre_op_tani', sa.String(length=255), nullable=True),
    sa.Column('post_op_tani', sa.String(length=255), nullable=True),
    sa.Column('ekip', sa.Text(), nullable=True),
    sa.Column('hemsire', sa.String(length=100), nullable=True),
    sa.Column('anestezi_ekip', sa.String(length=100), nullable=True),
    sa.Column('anestezi_tur', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('patoloji', sa.Text(), nullable=True),
    sa.Column('post_op', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_operasyonlar_hasta_id'), 'sharded_clinical_operasyonlar', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_operasyonlar_id'), 'sharded_clinical_operasyonlar', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_tetkikler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('tetkik_adi', sa.String(length=255), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(length=50), nullable=True),
    sa.Column('referans_araligi', sa.String(length=100), nullable=True),
    sa.Column('sembol', sa.String(length=50), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=255), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_tetkikler_hasta_id'), 'sharded_clinical_tetkikler', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_tetkikler_id'), 'sharded_clinical_tetkikler', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_tibbi_mudahale_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_basligi', sa.String(length=255), nullable=True),
    sa.Column('islem_detayi', sa.Text(), nullable=True),
    sa.Column('sonuc_oneriler', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_tibbi_mudahale_raporlari_hasta_id'), 'sharded_clinical_tibbi_mudahale_raporlari', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_tibbi_mudahale_raporlari_id'), 'sharded_clinical_tibbi_mudahale_raporlari', ['id'], unique=False, schema='clinical')
    op.create_table('sharded_clinical_trus_biyopsileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('psa_total', sa.String(length=50), nullable=True),
    sa.Column('rektal_tuse', sa.Text(), nullable=True),
    sa.Column('mri_var', sa.Boolean(), nullable=True),
    sa.Column('mri_tarih', sa.DateTime(), nullable=True),
    sa.Column('mri_ozet', sa.Text(), nullable=True),
    sa.Column('pirads_lezyon_boyut', sa.String(length=100), nullable=True),
    sa.Column('pirads_lezyon_lokasyon', sa.String(length=100), nullable=True),
    sa.Column('lokasyonlar', sa.Text(), nullable=True),
    sa.Column('prosedur_notu', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_trus_biyopsileri_hasta_id'), 'sharded_clinical_trus_biyopsileri', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_trus_biyopsileri_id'), 'sharded_clinical_trus_biyopsileri', ['id'], unique=False, schema='clinical')
    op.create_table('finans_hizmetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('varsayilan_fiyat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_finans_hizmetler_id'), 'finans_hizmetler', ['id'], unique=False, schema='finance')
    op.create_table('finans_kategoriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('ust_kategori_id', sa.Integer(), nullable=True),
    sa.Column('renk', sa.String(length=7), nullable=True),
    sa.Column('ikon', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_finans_kategoriler_id'), 'finans_kategoriler', ['id'], unique=False, schema='finance')
    op.create_table('kasalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('banka_adi', sa.String(length=100), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_kasalar_id'), 'kasalar', ['id'], unique=False, schema='finance')
    op.create_table('sharded_finance_islemler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referans_kodu', sa.String(length=20), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('muayene_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_sharded_finance_islemler_hasta_id'), 'sharded_finance_islemler', ['hasta_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_sharded_finance_islemler_id'), 'sharded_finance_islemler', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_sharded_finance_islemler_muayene_id'), 'sharded_finance_islemler', ['muayene_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_sharded_finance_islemler_referans_kodu'), 'sharded_finance_islemler', ['referans_kodu'], unique=True, schema='finance')
    op.create_table('sharded_patient_demographics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=10), nullable=True),
    sa.Column('cep_tel', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.String(length=255), nullable=True),
    sa.Column('dogum_yeri', sa.String(length=100), nullable=True),
    sa.Column('kan_grubu', sa.String(length=10), nullable=True),
    sa.Column('medeni_hal', sa.String(length=20), nullable=True),
    sa.Column('meslek', sa.String(length=100), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('kimlik_notlar', sa.String(), nullable=True),
    sa.Column('protokol_no', sa.String(length=50), nullable=True),
    sa.Column('ev_tel', sa.String(length=20), nullable=True),
    sa.Column('is_tel', sa.String(length=20), nullable=True),
    sa.Column('referans', sa.String(length=100), nullable=True),
    sa.Column('postakodu', sa.String(length=10), nullable=True),
    sa.Column('kurum', sa.String(length=100), nullable=True),
    sa.Column('sigorta', sa.String(length=100), nullable=True),
    sa.Column('ozelsigorta', sa.String(length=100), nullable=True),
    sa.Column('cocuk_sayisi', sa.Integer(), nullable=True),
    sa.Column('sms_izin', sa.Boolean(), nullable=True),
    sa.Column('email_izin', sa.Boolean(), nullable=True),
    sa.Column('iletisim_kaynagi', sa.String(length=50), nullable=True),
    sa.Column('iletisim_tercihi', sa.String(length=50), nullable=True),
    sa.Column('indirim_grubu', sa.String(length=50), nullable=True),
    sa.Column('dil', sa.String(length=20), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('kayit_notu', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='patient'
    )
    op.create_index(op.f('ix_patient_sharded_patient_demographics_id'), 'sharded_patient_demographics', ['id'], unique=False, schema='patient')
    op.create_index(op.f('ix_patient_sharded_patient_demographics_tc_kimlik'), 'sharded_patient_demographics', ['tc_kimlik'], unique=False, schema='patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_sharded_patient_demographics_tc_kimlik'), table_name='sharded_patient_demographics', schema='patient')
    op.drop_index(op.f('ix_patient_sharded_patient_demographics_id'), table_name='sharded_patient_demographics', schema='patient')
    op.drop_table('sharded_patient_demographics', schema='patient')
    op.drop_index(op.f('ix_finance_sharded_finance_islemler_referans_kodu'), table_name='sharded_finance_islemler', schema='finance')
    op.drop_index(op.f('ix_finance_sharded_finance_islemler_muayene_id'), table_name='sharded_finance_islemler', schema='finance')
    op.drop_index(op.f('ix_finance_sharded_finance_islemler_id'), table_name='sharded_finance_islemler', schema='finance')
    op.drop_index(op.f('ix_finance_sharded_finance_islemler_hasta_id'), table_name='sharded_finance_islemler', schema='finance')
    op.drop_table('sharded_finance_islemler', schema='finance')
    op.drop_index(op.f('ix_finance_kasalar_id'), table_name='kasalar', schema='finance')
    op.drop_table('kasalar', schema='finance')
    op.drop_index(op.f('ix_finance_finans_kategoriler_id'), table_name='finans_kategoriler', schema='finance')
    op.drop_table('finans_kategoriler', schema='finance')
    op.drop_index(op.f('ix_finance_finans_hizmetler_id'), table_name='finans_hizmetler', schema='finance')
    op.drop_table('finans_hizmetler', schema='finance')
    op.drop_index(op.f('ix_clinical_sharded_clinical_trus_biyopsileri_id'), table_name='sharded_clinical_trus_biyopsileri', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_trus_biyopsileri_hasta_id'), table_name='sharded_clinical_trus_biyopsileri', schema='clinical')
    op.drop_table('sharded_clinical_trus_biyopsileri', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_tibbi_mudahale_raporlari_id'), table_name='sharded_clinical_tibbi_mudahale_raporlari', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_tibbi_mudahale_raporlari_hasta_id'), table_name='sharded_clinical_tibbi_mudahale_raporlari', schema='clinical')
    op.drop_table('sharded_clinical_tibbi_mudahale_raporlari', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_tetkikler_id'), table_name='sharded_clinical_tetkikler', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_tetkikler_hasta_id'), table_name='sharded_clinical_tetkikler', schema='clinical')
    op.drop_table('sharded_clinical_tetkikler', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_operasyonlar_id'), table_name='sharded_clinical_operasyonlar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_operasyonlar_hasta_id'), table_name='sharded_clinical_operasyonlar', schema='clinical')
    op.drop_table('sharded_clinical_operasyonlar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_notlar_id'), table_name='sharded_clinical_notlar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_notlar_hasta_id'), table_name='sharded_clinical_notlar', schema='clinical')
    op.drop_table('sharded_clinical_notlar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_muayeneler_id'), table_name='sharded_clinical_muayeneler', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_muayeneler_hasta_id'), table_name='sharded_clinical_muayeneler', schema='clinical')
    op.drop_table('sharded_clinical_muayeneler', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_istirahat_raporlari_id'), table_name='sharded_clinical_istirahat_raporlari', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_istirahat_raporlari_hasta_id'), table_name='sharded_clinical_istirahat_raporlari', schema='clinical')
    op.drop_table('sharded_clinical_istirahat_raporlari', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_fotograflar_id'), table_name='sharded_clinical_fotograflar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_fotograflar_hasta_id'), table_name='sharded_clinical_fotograflar', schema='clinical')
    op.drop_table('sharded_clinical_fotograflar', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_durum_bildirir_raporlari_id'), table_name='sharded_clinical_durum_bildirir_raporlari', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_durum_bildirir_raporlari_hasta_id'), table_name='sharded_clinical_durum_bildirir_raporlari', schema='clinical')
    op.drop_table('sharded_clinical_durum_bildirir_raporlari', schema='clinical')
    # ### end Alembic commands ###
