"""Add stock module tables

Revision ID: 4df55a25f3c5
Revises: baf6f4a122d5
Create Date: 2026-01-02 21:57:06.871727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df55a25f3c5'
down_revision: Union[str, None] = 'baf6f4a122d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stok_urunler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=255), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=True),
    sa.Column('urun_tipi', sa.String(length=50), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mevcut_stok', sa.Integer(), nullable=True),
    sa.Column('min_stok', sa.Integer(), nullable=True),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_urunler_barkod'), 'stok_urunler', ['barkod'], unique=False)
    op.create_index(op.f('ix_stok_urunler_id'), 'stok_urunler', ['id'], unique=False)
    op.create_index(op.f('ix_stok_urunler_marka'), 'stok_urunler', ['marka'], unique=False)
    op.create_index(op.f('ix_stok_urunler_urun_adi'), 'stok_urunler', ['urun_adi'], unique=False)
    
    op.create_table('stok_alimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('alim_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('toplam_tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firmalar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stok_urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_alimlari_id'), 'stok_alimlari', ['id'], unique=False)
    
    op.create_table('stok_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('hareket_tipi', sa.String(), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kaynak', sa.String(length=50), nullable=True),
    sa.Column('kaynak_ref', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stok_urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_hareketleri_id'), 'stok_hareketleri', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stok_hareketleri_id'), table_name='stok_hareketleri')
    op.drop_table('stok_hareketleri')
    op.drop_index(op.f('ix_stok_alimlari_id'), table_name='stok_alimlari')
    op.drop_table('stok_alimlari')
    op.drop_index(op.f('ix_stok_urunler_urun_adi'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_marka'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_id'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_barkod'), table_name='stok_urunler')
    op.drop_table('stok_urunler')
    # ### end Alembic commands ###
