"""add_tani3_tani4_tani5_to_muayene

Revision ID: 640bf5f2ae8c
Revises: b3965612a132
Create Date: 2026-01-30 10:42:12.664865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640bf5f2ae8c'
down_revision: Union[str, None] = 'b3965612a132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
