"""initial_schema_with_uuid

Revision ID: 73893917c4c2
Revises: 
Create Date: 2025-12-29 18:26:26.414099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73893917c4c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekip_uyeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(), nullable=False),
    sa.Column('gorev', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ekip_uyeleri_id'), 'ekip_uyeleri', ['id'], unique=False)
    op.create_table('hastalar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tc_kimlik', sa.String(), nullable=True),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('soyad', sa.String(), nullable=True),
    sa.Column('cinsiyet', sa.String(), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('dogum_yeri', sa.String(), nullable=True),
    sa.Column('kan_grubu', sa.String(), nullable=True),
    sa.Column('medeni_hal', sa.String(), nullable=True),
    sa.Column('meslek', sa.String(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('ev_tel', sa.String(), nullable=True),
    sa.Column('is_tel', sa.String(), nullable=True),
    sa.Column('cep_tel', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('kimlik_notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('referans', sa.String(), nullable=True),
    sa.Column('postakodu', sa.String(), nullable=True),
    sa.Column('kurum', sa.String(), nullable=True),
    sa.Column('sigorta', sa.String(), nullable=True),
    sa.Column('ozelsigorta', sa.String(), nullable=True),
    sa.Column('cocuk_sayisi', sa.String(), nullable=True),
    sa.Column('faks', sa.String(), nullable=True),
    sa.Column('sms_izin', sa.String(), nullable=True),
    sa.Column('email_izin', sa.String(), nullable=True),
    sa.Column('iletisim_kaynagi', sa.String(), nullable=True),
    sa.Column('iletisim_tercihi', sa.String(), nullable=True),
    sa.Column('indirim_grubu', sa.String(), nullable=True),
    sa.Column('dil', sa.String(), nullable=True),
    sa.Column('personel_ids', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('kayit_notu', sa.Text(), nullable=True),
    sa.Column('protokol_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hastalar_ad'), 'hastalar', ['ad'], unique=False)
    op.create_index(op.f('ix_hastalar_id'), 'hastalar', ['id'], unique=False)
    op.create_index(op.f('ix_hastalar_protokol_no'), 'hastalar', ['protokol_no'], unique=False)
    op.create_index(op.f('ix_hastalar_soyad'), 'hastalar', ['soyad'], unique=False)
    op.create_index(op.f('ix_hastalar_tc_kimlik'), 'hastalar', ['tc_kimlik'], unique=True)
    op.create_table('hizmet_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('fiyat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hizmet_tanimlari_id'), 'hizmet_tanimlari', ['id'], unique=False)
    op.create_table('icd_tanilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kodu', sa.String(), nullable=False),
    sa.Column('adi', sa.String(), nullable=True),
    sa.Column('ust_kodu', sa.String(), nullable=True),
    sa.Column('aktif', sa.String(), nullable=True),
    sa.Column('seviye', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd_tanilar_adi'), 'icd_tanilar', ['adi'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_id'), 'icd_tanilar', ['id'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_kodu'), 'icd_tanilar', ['kodu'], unique=True)
    op.create_table('ilac_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('etkin_madde', sa.String(), nullable=True),
    sa.Column('atc_kodu', sa.String(), nullable=True),
    sa.Column('fiyat', sa.String(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('recete_tipi', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ilac_tanimlari_barcode'), 'ilac_tanimlari', ['barcode'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_id'), 'ilac_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_name'), 'ilac_tanimlari', ['name'], unique=False)
    op.create_table('kasa_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('para_birimi', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasa_tanimlari_id'), 'kasa_tanimlari', ['id'], unique=False)
    op.create_table('kurumlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('vergi_dairesi', sa.String(), nullable=True),
    sa.Column('vergi_no', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('faks', sa.String(), nullable=True),
    sa.Column('yetkili', sa.String(), nullable=True),
    sa.Column('notlar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurumlar_id'), 'kurumlar', ['id'], unique=False)
    op.create_table('sablon_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup', sa.String(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('icerik', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sablon_tanimlari_grup'), 'sablon_tanimlari', ['grup'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_id'), 'sablon_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_kod'), 'sablon_tanimlari', ['kod'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anamnezler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('alkol', sa.String(), nullable=True),
    sa.Column('sigara', sa.String(), nullable=True),
    sa.Column('allerji', sa.Text(), nullable=True),
    sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('soygecmis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hasta_id')
    )
    op.create_index(op.f('ix_anamnezler_id'), 'anamnezler', ['id'], unique=False)
    op.create_table('durum_bildirir_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tani_bulgular', sa.Text(), nullable=True),
    sa.Column('icd_kodu', sa.String(), nullable=True),
    sa.Column('sonuc_kanaat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), 'durum_bildirir_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_durum_bildirir_raporlari_id'), 'durum_bildirir_raporlari', ['id'], unique=False)
    op.create_index(op.f('ix_durum_bildirir_raporlari_tarih'), 'durum_bildirir_raporlari', ['tarih'], unique=False)
    op.create_table('fotograf_arsivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('asama', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotograf_arsivi_hasta_id'), 'fotograf_arsivi', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_fotograf_arsivi_id'), 'fotograf_arsivi', ['id'], unique=False)
    op.create_index(op.f('ix_fotograf_arsivi_tarih'), 'fotograf_arsivi', ['tarih'], unique=False)
    op.create_table('genel_lab_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('referans_araligi', sa.String(), nullable=True),
    sa.Column('bayrak', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genel_lab_sonuclari_id'), 'genel_lab_sonuclari', ['id'], unique=False)
    op.create_table('goruntuleme_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goruntuleme_sonuclari_id'), 'goruntuleme_sonuclari', ['id'], unique=False)
    op.create_table('hasta_dosyalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dosya_tipi', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('legacy_data', sa.LargeBinary(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('arsiv_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_dosyalari_id'), 'hasta_dosyalari', ['id'], unique=False)
    op.create_table('hasta_finans_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_tipi', sa.String(), nullable=False),
    sa.Column('hizmet_id', sa.Integer(), nullable=True),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('odeme_yontemi', sa.String(), nullable=True),
    sa.Column('aciklama', sa.String(), nullable=True),
    sa.Column('borc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('alacak', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bakiye', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.ForeignKeyConstraint(['hizmet_id'], ['hizmet_tanimlari.id'], ),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasa_tanimlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_finans_hareketleri_hasta_id'), 'hasta_finans_hareketleri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_hasta_finans_hareketleri_id'), 'hasta_finans_hareketleri', ['id'], unique=False)
    op.create_index(op.f('ix_hasta_finans_hareketleri_tarih'), 'hasta_finans_hareketleri', ['tarih'], unique=False)
    op.create_table('hasta_notlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasta_notlari_hasta_id'), 'hasta_notlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_hasta_notlari_id'), 'hasta_notlari', ['id'], unique=False)
    op.create_index(op.f('ix_hasta_notlari_tarih'), 'hasta_notlari', ['tarih'], unique=False)
    op.create_table('idrar_tahlilleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dansite', sa.String(), nullable=True),
    sa.Column('ph', sa.String(), nullable=True),
    sa.Column('sediment', sa.Text(), nullable=True),
    sa.Column('steril', sa.String(), nullable=True),
    sa.Column('koloni', sa.String(), nullable=True),
    sa.Column('bakteri', sa.String(), nullable=True),
    sa.Column('antibiyogram', sa.Text(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idrar_tahlilleri_id'), 'idrar_tahlilleri', ['id'], unique=False)
    op.create_table('istirahat_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('icd_kodu', sa.String(), nullable=True),
    sa.Column('tani', sa.Text(), nullable=True),
    sa.Column('karar', sa.String(), nullable=True),
    sa.Column('kontrol_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_istirahat_raporlari_hasta_id'), 'istirahat_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_istirahat_raporlari_id'), 'istirahat_raporlari', ['id'], unique=False)
    op.create_index(op.f('ix_istirahat_raporlari_tarih'), 'istirahat_raporlari', ['tarih'], unique=False)
    op.create_table('lab_uroflowmetri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('qmax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_flow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('residual_urine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_uroflowmetri_id'), 'lab_uroflowmetri', ['id'], unique=False)
    op.create_table('muayeneler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('sikayet', sa.Text(), nullable=True),
    sa.Column('oyku', sa.Text(), nullable=True),
    sa.Column('tansiyon', sa.String(), nullable=True),
    sa.Column('ates', sa.String(), nullable=True),
    sa.Column('kvah', sa.String(), nullable=True),
    sa.Column('bobrek_sag', sa.String(), nullable=True),
    sa.Column('bobrek_sol', sa.String(), nullable=True),
    sa.Column('suprapubik_kitle', sa.String(), nullable=True),
    sa.Column('ego', sa.String(), nullable=True),
    sa.Column('rektal_tuse', sa.String(), nullable=True),
    sa.Column('tani1', sa.String(), nullable=True),
    sa.Column('tani1_kodu', sa.String(), nullable=True),
    sa.Column('tani2', sa.String(), nullable=True),
    sa.Column('tani2_kodu', sa.String(), nullable=True),
    sa.Column('oneriler', sa.Text(), nullable=True),
    sa.Column('tedavi', sa.Text(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('prosedur', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('bulgu_notu', sa.Text(), nullable=True),
    sa.Column('recete', sa.Text(), nullable=True),
    sa.Column('disuri', sa.String(), nullable=True),
    sa.Column('pollakiuri', sa.String(), nullable=True),
    sa.Column('nokturi', sa.String(), nullable=True),
    sa.Column('hematuri', sa.String(), nullable=True),
    sa.Column('genital_akinti', sa.String(), nullable=True),
    sa.Column('kabizlik', sa.String(), nullable=True),
    sa.Column('tas_oyku', sa.String(), nullable=True),
    sa.Column('catallanma', sa.String(), nullable=True),
    sa.Column('projeksiyon_azalma', sa.String(), nullable=True),
    sa.Column('kalibre_incelme', sa.String(), nullable=True),
    sa.Column('idrar_bas_zorluk', sa.String(), nullable=True),
    sa.Column('kesik_idrar_yapma', sa.String(), nullable=True),
    sa.Column('terminal_damlama', sa.String(), nullable=True),
    sa.Column('residiv_hissi', sa.String(), nullable=True),
    sa.Column('inkontinans', sa.String(), nullable=True),
    sa.Column('erektil_islev', sa.String(), nullable=True),
    sa.Column('ejakulasyon', sa.String(), nullable=True),
    sa.Column('mshq', sa.String(), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('soygecmis', sa.Text(), nullable=True),
    sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True),
    sa.Column('kan_sulandirici', sa.Integer(), nullable=True),
    sa.Column('aliskanliklar', sa.Text(), nullable=True),
    sa.Column('sistem_sorgu', sa.Text(), nullable=True),
    sa.Column('ipss_skor', sa.String(), nullable=True),
    sa.Column('iief_ef_skor', sa.String(), nullable=True),
    sa.Column('iief_ef_answers', sa.Text(), nullable=True),
    sa.Column('fizik_muayene', sa.Text(), nullable=True),
    sa.Column('allerjiler', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muayeneler_hasta_id'), 'muayeneler', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_muayeneler_id'), 'muayeneler', ['id'], unique=False)
    op.create_index(op.f('ix_muayeneler_tarih'), 'muayeneler', ['tarih'], unique=False)
    op.create_table('operasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('ameliyat', sa.String(), nullable=True),
    sa.Column('pre_op_tani', sa.String(), nullable=True),
    sa.Column('post_op_tani', sa.String(), nullable=True),
    sa.Column('ekip', sa.Text(), nullable=True),
    sa.Column('hemsire', sa.String(), nullable=True),
    sa.Column('anestezi_ekip', sa.String(), nullable=True),
    sa.Column('anestezi_tur', sa.String(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('patoloji', sa.Text(), nullable=True),
    sa.Column('post_op', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operasyonlar_hasta_id'), 'operasyonlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_operasyonlar_id'), 'operasyonlar', ['id'], unique=False)
    op.create_index(op.f('ix_operasyonlar_tarih'), 'operasyonlar', ['tarih'], unique=False)
    op.create_table('planlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('yapildi', sa.String(), nullable=True),
    sa.Column('hatirlat', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planlar_hasta_id'), 'planlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_planlar_id'), 'planlar', ['id'], unique=False)
    op.create_index(op.f('ix_planlar_tarih'), 'planlar', ['tarih'], unique=False)
    op.create_table('randevular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randevular_hasta_id'), 'randevular', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_randevular_id'), 'randevular', ['id'], unique=False)
    op.create_index(op.f('ix_randevular_start'), 'randevular', ['start'], unique=False)
    op.create_table('sperm_analizleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('perhiz', sa.String(), nullable=True),
    sa.Column('volum', sa.String(), nullable=True),
    sa.Column('likefaksiyon', sa.String(), nullable=True),
    sa.Column('viskozite', sa.String(), nullable=True),
    sa.Column('aglutinasyon', sa.String(), nullable=True),
    sa.Column('yuvarlak_hucre', sa.String(), nullable=True),
    sa.Column('sayi', sa.String(), nullable=True),
    sa.Column('motilite', sa.String(), nullable=True),
    sa.Column('p_motilite', sa.String(), nullable=True),
    sa.Column('tpmss', sa.String(), nullable=True),
    sa.Column('kruger', sa.String(), nullable=True),
    sa.Column('metod', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sperm_analizleri_id'), 'sperm_analizleri', ['id'], unique=False)
    op.create_table('telefon_gorusmeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefon_gorusmeleri_hasta_id'), 'telefon_gorusmeleri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_telefon_gorusmeleri_id'), 'telefon_gorusmeleri', ['id'], unique=False)
    op.create_index(op.f('ix_telefon_gorusmeleri_tarih'), 'telefon_gorusmeleri', ['tarih'], unique=False)
    op.create_table('tetkik_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('tetkik_adi', sa.String(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('referans_araligi', sa.String(), nullable=True),
    sa.Column('sembol', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tetkik_sonuclari_hasta_id'), 'tetkik_sonuclari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tetkik_sonuclari_id'), 'tetkik_sonuclari', ['id'], unique=False)
    op.create_index(op.f('ix_tetkik_sonuclari_tarih'), 'tetkik_sonuclari', ['tarih'], unique=False)
    op.create_table('tibbi_mudahale_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_basligi', sa.String(), nullable=True),
    sa.Column('islem_detayi', sa.Text(), nullable=True),
    sa.Column('sonuc_oneriler', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), 'tibbi_mudahale_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_id'), 'tibbi_mudahale_raporlari', ['id'], unique=False)
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_tarih'), 'tibbi_mudahale_raporlari', ['tarih'], unique=False)
    op.create_table('urodinamiler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('qmax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_flow', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voided_volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('residual_urine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sistometry', sa.Text(), nullable=True),
    sa.Column('bac', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urodinamiler_id'), 'urodinamiler', ['id'], unique=False)
    op.create_table('user_oauth',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_urodinamiler_id'), table_name='urodinamiler')
    op.drop_table('urodinamiler')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_tarih'), table_name='tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_table('tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tetkik_sonuclari_tarih'), table_name='tetkik_sonuclari')
    op.drop_index(op.f('ix_tetkik_sonuclari_id'), table_name='tetkik_sonuclari')
    op.drop_index(op.f('ix_tetkik_sonuclari_hasta_id'), table_name='tetkik_sonuclari')
    op.drop_table('tetkik_sonuclari')
    op.drop_index(op.f('ix_telefon_gorusmeleri_tarih'), table_name='telefon_gorusmeleri')
    op.drop_index(op.f('ix_telefon_gorusmeleri_id'), table_name='telefon_gorusmeleri')
    op.drop_index(op.f('ix_telefon_gorusmeleri_hasta_id'), table_name='telefon_gorusmeleri')
    op.drop_table('telefon_gorusmeleri')
    op.drop_index(op.f('ix_sperm_analizleri_id'), table_name='sperm_analizleri')
    op.drop_table('sperm_analizleri')
    op.drop_index(op.f('ix_randevular_start'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_id'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_hasta_id'), table_name='randevular')
    op.drop_table('randevular')
    op.drop_index(op.f('ix_planlar_tarih'), table_name='planlar')
    op.drop_index(op.f('ix_planlar_id'), table_name='planlar')
    op.drop_index(op.f('ix_planlar_hasta_id'), table_name='planlar')
    op.drop_table('planlar')
    op.drop_index(op.f('ix_operasyonlar_tarih'), table_name='operasyonlar')
    op.drop_index(op.f('ix_operasyonlar_id'), table_name='operasyonlar')
    op.drop_index(op.f('ix_operasyonlar_hasta_id'), table_name='operasyonlar')
    op.drop_table('operasyonlar')
    op.drop_index(op.f('ix_muayeneler_tarih'), table_name='muayeneler')
    op.drop_index(op.f('ix_muayeneler_id'), table_name='muayeneler')
    op.drop_index(op.f('ix_muayeneler_hasta_id'), table_name='muayeneler')
    op.drop_table('muayeneler')
    op.drop_index(op.f('ix_lab_uroflowmetri_id'), table_name='lab_uroflowmetri')
    op.drop_table('lab_uroflowmetri')
    op.drop_index(op.f('ix_istirahat_raporlari_tarih'), table_name='istirahat_raporlari')
    op.drop_index(op.f('ix_istirahat_raporlari_id'), table_name='istirahat_raporlari')
    op.drop_index(op.f('ix_istirahat_raporlari_hasta_id'), table_name='istirahat_raporlari')
    op.drop_table('istirahat_raporlari')
    op.drop_index(op.f('ix_idrar_tahlilleri_id'), table_name='idrar_tahlilleri')
    op.drop_table('idrar_tahlilleri')
    op.drop_index(op.f('ix_hasta_notlari_tarih'), table_name='hasta_notlari')
    op.drop_index(op.f('ix_hasta_notlari_id'), table_name='hasta_notlari')
    op.drop_index(op.f('ix_hasta_notlari_hasta_id'), table_name='hasta_notlari')
    op.drop_table('hasta_notlari')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_tarih'), table_name='hasta_finans_hareketleri')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_id'), table_name='hasta_finans_hareketleri')
    op.drop_index(op.f('ix_hasta_finans_hareketleri_hasta_id'), table_name='hasta_finans_hareketleri')
    op.drop_table('hasta_finans_hareketleri')
    op.drop_index(op.f('ix_hasta_dosyalari_id'), table_name='hasta_dosyalari')
    op.drop_table('hasta_dosyalari')
    op.drop_index(op.f('ix_goruntuleme_sonuclari_id'), table_name='goruntuleme_sonuclari')
    op.drop_table('goruntuleme_sonuclari')
    op.drop_index(op.f('ix_genel_lab_sonuclari_id'), table_name='genel_lab_sonuclari')
    op.drop_table('genel_lab_sonuclari')
    op.drop_index(op.f('ix_fotograf_arsivi_tarih'), table_name='fotograf_arsivi')
    op.drop_index(op.f('ix_fotograf_arsivi_id'), table_name='fotograf_arsivi')
    op.drop_index(op.f('ix_fotograf_arsivi_hasta_id'), table_name='fotograf_arsivi')
    op.drop_table('fotograf_arsivi')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_tarih'), table_name='durum_bildirir_raporlari')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_id'), table_name='durum_bildirir_raporlari')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), table_name='durum_bildirir_raporlari')
    op.drop_table('durum_bildirir_raporlari')
    op.drop_index(op.f('ix_anamnezler_id'), table_name='anamnezler')
    op.drop_table('anamnezler')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sablon_tanimlari_kod'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_id'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_grup'), table_name='sablon_tanimlari')
    op.drop_table('sablon_tanimlari')
    op.drop_index(op.f('ix_kurumlar_id'), table_name='kurumlar')
    op.drop_table('kurumlar')
    op.drop_index(op.f('ix_kasa_tanimlari_id'), table_name='kasa_tanimlari')
    op.drop_table('kasa_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_name'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_id'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_barcode'), table_name='ilac_tanimlari')
    op.drop_table('ilac_tanimlari')
    op.drop_index(op.f('ix_icd_tanilar_kodu'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_id'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_adi'), table_name='icd_tanilar')
    op.drop_table('icd_tanilar')
    op.drop_index(op.f('ix_hizmet_tanimlari_id'), table_name='hizmet_tanimlari')
    op.drop_table('hizmet_tanimlari')
    op.drop_index(op.f('ix_hastalar_tc_kimlik'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_soyad'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_protokol_no'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_id'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_ad'), table_name='hastalar')
    op.drop_table('hastalar')
    op.drop_index(op.f('ix_ekip_uyeleri_id'), table_name='ekip_uyeleri')
    op.drop_table('ekip_uyeleri')
    # ### end Alembic commands ###
