"""align_sharded_audit_and_legacy_columns_final

Revision ID: 746c1a695148
Revises: 8b604bde891d
Create Date: 2026-01-31 19:58:33.371592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746c1a695148'
down_revision: Union[str, None] = '8b604bde891d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharded_clinical_telefon_gorusmeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_sharded_clinical_telefon_gorusmeleri_hasta_id'), 'sharded_clinical_telefon_gorusmeleri', ['hasta_id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_sharded_clinical_telefon_gorusmeleri_id'), 'sharded_clinical_telefon_gorusmeleri', ['id'], unique=False, schema='clinical')
    op.create_table('finans_islem_satirlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('islem_id', sa.Integer(), nullable=False),
    sa.Column('hizmet_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_finans_islem_satirlari_id'), 'finans_islem_satirlari', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_finans_islem_satirlari_islem_id'), 'finans_islem_satirlari', ['islem_id'], unique=False, schema='finance')
    op.create_table('finans_odemeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('islem_id', sa.Integer(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('odeme_yontemi', sa.String(length=50), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odeme_tarihi', sa.Date(), nullable=False),
    sa.Column('taksit_sayisi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_finans_odemeler_id'), 'finans_odemeler', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_finans_odemeler_islem_id'), 'finans_odemeler', ['islem_id'], unique=False, schema='finance')
    op.create_table('finans_taksitler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odeme_id', sa.Integer(), nullable=False),
    sa.Column('taksit_no', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_finans_taksitler_id'), 'finans_taksitler', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_finans_taksitler_odeme_id'), 'finans_taksitler', ['odeme_id'], unique=False, schema='finance')
    op.create_table('firmalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_no', sa.String(length=20), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('yetkili', sa.String(length=100), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_firmalar_id'), 'firmalar', ['id'], unique=False, schema='finance')
    op.create_table('kasa_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=False),
    sa.Column('hareket_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('onceki_bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sonraki_bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('islem_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_kasa_hareketleri_id'), 'kasa_hareketleri', ['id'], unique=False, schema='finance')
    op.add_column('sharded_clinical_durum_bildirir_raporlari', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_durum_bildirir_raporlari', sa.Column('created_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_durum_bildirir_raporlari', sa.Column('updated_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_istirahat_raporlari', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_istirahat_raporlari', sa.Column('created_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_istirahat_raporlari', sa.Column('updated_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_tibbi_mudahale_raporlari', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_tibbi_mudahale_raporlari', sa.Column('created_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_tibbi_mudahale_raporlari', sa.Column('updated_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_trus_biyopsileri', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_trus_biyopsileri', sa.Column('created_by', sa.Integer(), nullable=True), schema='clinical')
    op.add_column('sharded_clinical_trus_biyopsileri', sa.Column('updated_by', sa.Integer(), nullable=True), schema='clinical')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharded_clinical_trus_biyopsileri', 'updated_by', schema='clinical')
    op.drop_column('sharded_clinical_trus_biyopsileri', 'created_by', schema='clinical')
    op.drop_column('sharded_clinical_trus_biyopsileri', 'updated_at', schema='clinical')
    op.drop_column('sharded_clinical_tibbi_mudahale_raporlari', 'updated_by', schema='clinical')
    op.drop_column('sharded_clinical_tibbi_mudahale_raporlari', 'created_by', schema='clinical')
    op.drop_column('sharded_clinical_tibbi_mudahale_raporlari', 'updated_at', schema='clinical')
    op.drop_column('sharded_clinical_istirahat_raporlari', 'updated_by', schema='clinical')
    op.drop_column('sharded_clinical_istirahat_raporlari', 'created_by', schema='clinical')
    op.drop_column('sharded_clinical_istirahat_raporlari', 'updated_at', schema='clinical')
    op.drop_column('sharded_clinical_durum_bildirir_raporlari', 'updated_by', schema='clinical')
    op.drop_column('sharded_clinical_durum_bildirir_raporlari', 'created_by', schema='clinical')
    op.drop_column('sharded_clinical_durum_bildirir_raporlari', 'updated_at', schema='clinical')
    op.drop_index(op.f('ix_finance_kasa_hareketleri_id'), table_name='kasa_hareketleri', schema='finance')
    op.drop_table('kasa_hareketleri', schema='finance')
    op.drop_index(op.f('ix_finance_firmalar_id'), table_name='firmalar', schema='finance')
    op.drop_table('firmalar', schema='finance')
    op.drop_index(op.f('ix_finance_finans_taksitler_odeme_id'), table_name='finans_taksitler', schema='finance')
    op.drop_index(op.f('ix_finance_finans_taksitler_id'), table_name='finans_taksitler', schema='finance')
    op.drop_table('finans_taksitler', schema='finance')
    op.drop_index(op.f('ix_finance_finans_odemeler_islem_id'), table_name='finans_odemeler', schema='finance')
    op.drop_index(op.f('ix_finance_finans_odemeler_id'), table_name='finans_odemeler', schema='finance')
    op.drop_table('finans_odemeler', schema='finance')
    op.drop_index(op.f('ix_finance_finans_islem_satirlari_islem_id'), table_name='finans_islem_satirlari', schema='finance')
    op.drop_index(op.f('ix_finance_finans_islem_satirlari_id'), table_name='finans_islem_satirlari', schema='finance')
    op.drop_table('finans_islem_satirlari', schema='finance')
    op.drop_index(op.f('ix_clinical_sharded_clinical_telefon_gorusmeleri_id'), table_name='sharded_clinical_telefon_gorusmeleri', schema='clinical')
    op.drop_index(op.f('ix_clinical_sharded_clinical_telefon_gorusmeleri_hasta_id'), table_name='sharded_clinical_telefon_gorusmeleri', schema='clinical')
    op.drop_table('sharded_clinical_telefon_gorusmeleri', schema='clinical')
    # ### end Alembic commands ###
