"""Add PIRADS fields to TrusBiyopsi

Revision ID: 964172eb296a
Revises: trus_biopsy_v1
Create Date: 2026-01-27 21:31:48.198835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '964172eb296a'
down_revision: Union[str, None] = 'trus_biopsy_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_constraint(op.f('hasta_finans_hareketleri_kasa_id_fkey'), 'hasta_finans_hareketleri', type_='foreignkey')
    op.drop_constraint(op.f('hasta_finans_hareketleri_hizmet_id_fkey'), 'hasta_finans_hareketleri', type_='foreignkey')
    op.drop_constraint(op.f('fk_hasta_finans_hareketleri_muayene_id'), 'hasta_finans_hareketleri', type_='foreignkey')
    op.create_foreign_key(None, 'hasta_finans_hareketleri', 'finans_hizmetler', ['hizmet_id'], ['id'])
    op.create_foreign_key(None, 'hasta_finans_hareketleri', 'kasalar', ['kasa_id'], ['id'])
    op.create_foreign_key(None, 'hasta_finans_hareketleri', 'muayeneler', ['muayene_id'], ['id'])
    op.add_column('kasa_tanimlari', sa.Column('bakiye', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('trus_biyopsileri', sa.Column('pirads_lezyon_boyut', sa.String(), nullable=True))
    op.add_column('trus_biyopsileri', sa.Column('pirads_lezyon_lokasyon', sa.String(), nullable=True))
    op.drop_constraint(op.f('trus_biyopsileri_hasta_id_fkey'), 'trus_biyopsileri', type_='foreignkey')
    op.create_foreign_key(None, 'trus_biyopsileri', 'hastalar', ['hasta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trus_biyopsileri', type_='foreignkey')
    op.create_foreign_key(op.f('trus_biyopsileri_hasta_id_fkey'), 'trus_biyopsileri', 'hastalar', ['hasta_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trus_biyopsileri', 'pirads_lezyon_lokasyon')
    op.drop_column('trus_biyopsileri', 'pirads_lezyon_boyut')
    op.drop_column('kasa_tanimlari', 'bakiye')
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='foreignkey')
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='foreignkey')
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='foreignkey')
    op.create_foreign_key(op.f('fk_hasta_finans_hareketleri_muayene_id'), 'hasta_finans_hareketleri', 'muayeneler', ['muayene_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('hasta_finans_hareketleri_hizmet_id_fkey'), 'hasta_finans_hareketleri', 'hizmet_tanimlari', ['hizmet_id'], ['id'])
    op.create_foreign_key(op.f('hasta_finans_hareketleri_kasa_id_fkey'), 'hasta_finans_hareketleri', 'kasa_tanimlari', ['kasa_id'], ['id'])
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
