"""fix_missing_kasa_columns

Revision ID: baf6f4a122d5
Revises: dde2f46421d6
Create Date: 2026-01-02 09:08:38.110546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf6f4a122d5'
down_revision: Union[str, None] = 'dde2f46421d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('finans_islem_satirlari_hizmet_id_fkey'), 'finans_islem_satirlari', type_='foreignkey')
    op.create_foreign_key(None, 'finans_islem_satirlari', 'finans_hizmetler', ['hizmet_id'], ['id'])
    op.drop_constraint(op.f('finans_islemler_referans_kodu_key'), 'finans_islemler', type_='unique')
    op.drop_index(op.f('ix_finans_islemler_islem_tipi'), table_name='finans_islemler')
    op.drop_index(op.f('ix_finans_islemler_tarih'), table_name='finans_islemler')
    op.drop_index(op.f('ix_finans_islemler_referans_kodu'), table_name='finans_islemler')
    op.create_index(op.f('ix_finans_islemler_referans_kodu'), 'finans_islemler', ['referans_kodu'], unique=True)
    op.drop_constraint(op.f('finans_islemler_kasa_id_fkey'), 'finans_islemler', type_='foreignkey')
    op.drop_constraint(op.f('finans_islemler_kategori_id_fkey'), 'finans_islemler', type_='foreignkey')
    op.drop_constraint(op.f('finans_islemler_firma_id_fkey'), 'finans_islemler', type_='foreignkey')
    op.drop_constraint(op.f('finans_islemler_muayene_id_fkey'), 'finans_islemler', type_='foreignkey')
    op.drop_constraint(op.f('finans_islemler_hasta_id_fkey'), 'finans_islemler', type_='foreignkey')
    op.create_foreign_key(None, 'finans_islemler', 'kasalar', ['kasa_id'], ['id'])
    op.create_foreign_key(None, 'finans_islemler', 'firmalar', ['firma_id'], ['id'])
    op.create_foreign_key(None, 'finans_islemler', 'hastalar', ['hasta_id'], ['id'])
    op.create_foreign_key(None, 'finans_islemler', 'muayeneler', ['muayene_id'], ['id'])
    op.create_foreign_key(None, 'finans_islemler', 'finans_kategoriler', ['kategori_id'], ['id'])
    op.drop_index(op.f('ix_finans_kategoriler_tip'), table_name='finans_kategoriler')
    op.drop_constraint(op.f('finans_kategoriler_ust_kategori_id_fkey'), 'finans_kategoriler', type_='foreignkey')
    op.create_foreign_key(None, 'finans_kategoriler', 'finans_kategoriler', ['ust_kategori_id'], ['id'])
    op.drop_constraint(op.f('finans_odemeler_kasa_id_fkey'), 'finans_odemeler', type_='foreignkey')
    op.create_foreign_key(None, 'finans_odemeler', 'kasalar', ['kasa_id'], ['id'])
    op.add_column('hasta_finans_hareketleri', sa.Column('odeme_araci', sa.String(length=100), nullable=True))
    op.add_column('hasta_finans_hareketleri', sa.Column('referans_kodu', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'hasta_finans_hareketleri', ['referans_kodu'])
    op.drop_index(op.f('ix_kasa_hareketler_tarih'), table_name='kasa_hareketler')
    op.drop_constraint(op.f('kasa_hareketler_odeme_id_fkey'), 'kasa_hareketler', type_='foreignkey')
    op.drop_constraint(op.f('kasa_hareketler_kasa_id_fkey'), 'kasa_hareketler', type_='foreignkey')
    op.drop_constraint(op.f('kasa_hareketler_islem_id_fkey'), 'kasa_hareketler', type_='foreignkey')
    op.create_foreign_key(None, 'kasa_hareketler', 'finans_islemler', ['islem_id'], ['id'])
    op.create_foreign_key(None, 'kasa_hareketler', 'finans_odemeler', ['odeme_id'], ['id'])
    op.create_foreign_key(None, 'kasa_hareketler', 'kasalar', ['kasa_id'], ['id'])
    op.add_column('kasalar', sa.Column('sira_no', sa.Integer(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('ph', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('total_sperm_sayisi', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_pr', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_np', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_im', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_4', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_3', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_2', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('motilite_1', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('morfoloji_bas', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('morfoloji_boyun', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('morfoloji_kuyruk', sa.String(), nullable=True))
    op.add_column('sperm_analizleri', sa.Column('notlar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sperm_analizleri', 'notlar')
    op.drop_column('sperm_analizleri', 'morfoloji_kuyruk')
    op.drop_column('sperm_analizleri', 'morfoloji_boyun')
    op.drop_column('sperm_analizleri', 'morfoloji_bas')
    op.drop_column('sperm_analizleri', 'motilite_1')
    op.drop_column('sperm_analizleri', 'motilite_2')
    op.drop_column('sperm_analizleri', 'motilite_3')
    op.drop_column('sperm_analizleri', 'motilite_4')
    op.drop_column('sperm_analizleri', 'motilite_im')
    op.drop_column('sperm_analizleri', 'motilite_np')
    op.drop_column('sperm_analizleri', 'motilite_pr')
    op.drop_column('sperm_analizleri', 'total_sperm_sayisi')
    op.drop_column('sperm_analizleri', 'ph')
    op.drop_column('kasalar', 'sira_no')
    op.drop_constraint(None, 'kasa_hareketler', type_='foreignkey')
    op.drop_constraint(None, 'kasa_hareketler', type_='foreignkey')
    op.drop_constraint(None, 'kasa_hareketler', type_='foreignkey')
    op.create_foreign_key(op.f('kasa_hareketler_islem_id_fkey'), 'kasa_hareketler', 'finans_islemler', ['islem_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('kasa_hareketler_kasa_id_fkey'), 'kasa_hareketler', 'kasalar', ['kasa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('kasa_hareketler_odeme_id_fkey'), 'kasa_hareketler', 'finans_odemeler', ['odeme_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_kasa_hareketler_tarih'), 'kasa_hareketler', ['tarih'], unique=False)
    op.drop_constraint(None, 'hasta_finans_hareketleri', type_='unique')
    op.drop_column('hasta_finans_hareketleri', 'referans_kodu')
    op.drop_column('hasta_finans_hareketleri', 'odeme_araci')
    op.drop_constraint(None, 'finans_odemeler', type_='foreignkey')
    op.create_foreign_key(op.f('finans_odemeler_kasa_id_fkey'), 'finans_odemeler', 'kasalar', ['kasa_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'finans_kategoriler', type_='foreignkey')
    op.create_foreign_key(op.f('finans_kategoriler_ust_kategori_id_fkey'), 'finans_kategoriler', 'finans_kategoriler', ['ust_kategori_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_finans_kategoriler_tip'), 'finans_kategoriler', ['tip'], unique=False)
    op.drop_constraint(None, 'finans_islemler', type_='foreignkey')
    op.drop_constraint(None, 'finans_islemler', type_='foreignkey')
    op.drop_constraint(None, 'finans_islemler', type_='foreignkey')
    op.drop_constraint(None, 'finans_islemler', type_='foreignkey')
    op.drop_constraint(None, 'finans_islemler', type_='foreignkey')
    op.create_foreign_key(op.f('finans_islemler_hasta_id_fkey'), 'finans_islemler', 'hastalar', ['hasta_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('finans_islemler_muayene_id_fkey'), 'finans_islemler', 'muayeneler', ['muayene_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('finans_islemler_firma_id_fkey'), 'finans_islemler', 'firmalar', ['firma_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('finans_islemler_kategori_id_fkey'), 'finans_islemler', 'finans_kategoriler', ['kategori_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('finans_islemler_kasa_id_fkey'), 'finans_islemler', 'kasalar', ['kasa_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_finans_islemler_referans_kodu'), table_name='finans_islemler')
    op.create_index(op.f('ix_finans_islemler_referans_kodu'), 'finans_islemler', ['referans_kodu'], unique=False)
    op.create_index(op.f('ix_finans_islemler_tarih'), 'finans_islemler', ['tarih'], unique=False)
    op.create_index(op.f('ix_finans_islemler_islem_tipi'), 'finans_islemler', ['islem_tipi'], unique=False)
    op.create_unique_constraint(op.f('finans_islemler_referans_kodu_key'), 'finans_islemler', ['referans_kodu'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'finans_islem_satirlari', type_='foreignkey')
    op.create_foreign_key(op.f('finans_islem_satirlari_hizmet_id_fkey'), 'finans_islem_satirlari', 'finans_hizmetler', ['hizmet_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
