import { SystemQueryData } from "./schema";

export const systemQueryAdapter = {
    toNew: (formData: any): SystemQueryData => ({
        disuri: formData.disuri || "",
        pollakiuri_text: formData.pollakiuri_text || "",
        nokturi_text: formData.nokturi_text || "",
        ates_sq: formData.ates_sq || "",
        genital_akinti: formData.genital_akinti || "",
        kabizlik: formData.kabizlik || "",
        tas_oyku: formData.tas_oyku || "",
        hematuri: formData.hematuri || "",
        catallanma: formData.catallanma || "",
        projeksiyon_azalma_sq: formData.projeksiyon_azalma_sq || "",
        kalibre_incelme: formData.kalibre_incelme || "",
        idrar_bas_zorluk_text: formData.idrar_bas_zorluk_text || "",
        kesik_idrar_yapma_text: formData.kesik_idrar_yapma_text || "",
        terminal_damlama: formData.terminal_damlama || "",
        residu_hissi_text: formData.residu_hissi_text || "",
        inkontinans: formData.inkontinans || "",
        erektil_islev: formData.erektil_islev || "",
        ejakulasyon: formData.ejakulasyon || "",
    }),
    toLegacy: (data: SystemQueryData): any => ({
        disuri: data.disuri,
        pollakiuri_text: data.pollakiuri_text,
        nokturi_text: data.nokturi_text,
        ates_sq: data.ates_sq,
        genital_akinti: data.genital_akinti,
        kabizlik: data.kabizlik,
        tas_oyku: data.tas_oyku,
        hematuri: data.hematuri,
        catallanma: data.catallanma,
        projeksiyon_azalma_sq: data.projeksiyon_azalma_sq,
        kalibre_incelme: data.kalibre_incelme,
        idrar_bas_zorluk_text: data.idrar_bas_zorluk_text,
        kesik_idrar_yapma_text: data.kesik_idrar_yapma_text,
        terminal_damlama: data.terminal_damlama,
        residu_hissi_text: data.residu_hissi_text,
        inkontinans: data.inkontinans,
        erektil_islev: data.erektil_islev,
        ejakulasyon: data.ejakulasyon,
    })
};
